formats: dict[str, list[str]] = {
    "audio": [
        "mp1", "mp2", "mp3",
        "ogg", "opus", "spx",
        "wav", "aif", "aiff",
        "m4a", "aac", "eac3", "ac3", "dts",
        "flac", "wv", "ape", "tta",
        "wma", "mka",
        "mpc", "ra",
        "amr", "caf",
        "s3m", "xm", "mod", "it",
    ],
    "video": [
        "flv", "f4v",
        "rm", "rmvb",
        "3gp",
        "mp4", "m4v",
        "mkv",
        "mov",
        "wmv", "asf",
        "mpeg", "mpg", "m2v",
        "avi", "divx",
        "webm",
        "ts", "m2ts", "mts",
        "vob",
        "ogv",
        "dv",
    ],
}

format_descriptions: dict[str, dict[str, str]] = {
    "audio": {
        "mp1":  "MPEG Audio Layer 1",
        "mp2":  "MPEG Audio Layer 2",
        "mp3":  "MPEG Audio Layer 3",
        "ogg":  "Ogg Vorbis Audio Container",
        "opus": "Opus Audio",
        "spx":  "Speex Audio",
        "wav":  "Waveform Audio File Format",
        "aif":  "Audio Interchange File Format",
        "aiff": "Audio Interchange File Format (AIFF)",
        "m4a":  "MPEG-4 Audio (often AAC)",
        "aac":  "Advanced Audio Coding",
        "eac3": "Enhanced AC-3 (Dolby Digital Plus)",
        "ac3":  "Dolby Digital AC-3",
        "dts":  "DTS Audio",
        "flac": "Free Lossless Audio Codec",
        "wv":   "WavPack Lossless Audio",
        "ape":  "Monkey's Audio (APE)",
        "tta":  "True Audio (TTA)",
        "wma":  "Windows Media Audio",
        "mka":  "Matroska Audio",
        "mpc":  "Musepack Audio",
        "ra":   "RealAudio",
        "amr":  "Adaptive Multi-Rate Audio",
        "caf":  "Core Audio Format",
        "s3m":  "Scream Tracker 3 Module",
        "xm":   "Extended Module (FastTracker 2)",
        "mod":  "MOD Tracker Module",
        "it":   "Impulse Tracker Module",
    },
    "video": {
        "flv":   "Flash Video",
        "f4v":   "Flash MP4 Video",
        "rm":    "RealMedia",
        "rmvb":  "RealMedia Variable Bitrate",
        "3gp":   "3rd Generation Partnership Project",
        "mp4":   "MPEG-4 Part 14 Video Container",
        "m4v":   "iTunes Video (MPEG-4)",
        "mkv":   "Matroska Multimedia Container",
        "mov":   "Apple QuickTime Movie",
        "wmv":   "Windows Media Video",
        "asf":   "Advanced Systems Format",
        "mpeg":  "Moving Picture Experts Group Video (MPEG-1/MPEG-2)",
        "mpg":   "MPEG Video",
        "m2v":   "MPEG-2 Video Elementary Stream",
        "avi":   "Audio Video Interleave",
        "divx":  "DivX Video",
        "webm":  "WebM Video Format (VP8/VP9/AV1 Video, Vorbis/Opus Audio)",
        "ts":    "MPEG-2 Transport Stream",
        "m2ts":  "Blu-ray MPEG-2 Transport Stream",
        "mts":   "AVCHD Video Transport Stream",
        "vob":   "DVD Video Object",
        "ogv":   "Ogg Video",
        "dv":    "Digital Video (DV)",
    },
}

image_extensions: set[str] = {
    ".png", ".jpg", ".jpeg",
    ".bmp",
    ".gif",
    ".xbm", ".xpm",
    ".pbm", ".pgm", ".ppm",
    ".tiff", ".tif",
    ".ico",
    ".svg", ".svgz",
    ".webp",
}
