key_dict = {
"Global": {
"Play/Pause":"Ctrl+Win+P",
"Mute/Unmute":"Ctrl+Win+M",
"Volume Down":"Ctrl+Win+F7",
"Volume Up":"Ctrl+Win+F8",
"Previous":"Ctrl+Win+F9",
"Next":"Ctrl+Win+F10"
},
"Main interface": {
"Open file": "Ctrl+O",
"Open folder": "Ctrl+Shift+O",
"Open URL":"Ctrl+U",
"Close Currently playing Media":"Ctrl+W",
"Show/Hide explorer": "Ctrl+E",
"Show/Hide player controls": "Ctrl+H",
"Show/Hide playlists": "Ctrl+L",
"Toggle playlists": "Ctrl+1",
"Toggle podcasts": "Ctrl+2",
"Toggle radio": "Ctrl+3",
"Toggle recents/favorites": "Ctrl+4",
"Focus playlists": "Alt+1",
"Focus podcasts": "Alt+2",
"Focus radio": "Alt+3",
"Focus recents/favorites": "Alt+4",
"Hide window": "Alt+H",
"Exit": "Alt+X",
"Focus explorer": "Alt+E",
"Focus player": "Alt+P",
"Documentation":"F1",
"Hotkeys dialog": "F4",
"Prefrences Dialog":"Ctrl+P"
},
"Explorer": {
"Play/Pause": "Space",
"Backward": "left",
"Forward": "right",
"Stop": "Ctrl+Space",
"Search files/folders": "F3",
},
"Player": {
"Play/Pause": "Space",
"Backward": "left",
"Forward": "right",
"Stop": "Ctrl+Space",
"Mute/Unmute":"M",
"Previous": "Page Up",
"Next": "Page Down",
"Jump to beginning": "Home",
"Jump to the end": "End",
"Toggle repeat": "Ctrl+r",
"Volume up": "up",
"Volume down": "down",
"Fullscreen": "F11",
"Exit fullscreen": "Esc",
"Take snapshot": "Ctrl+s",
"Bookmarks list": "Ctrl+B",
"Go to time": "Ctrl+G",
"New mark at current position": "K",
"Repeat loop start": "[",
"Repeat loop end": "]",
"Clear repeat loop":"backspace",
"Previous repeat loop":"Ctrl+[",
"Next repeat loop":"Ctrl+]",
"Delete current bookmark":"Delete",
"Previous bookmark":"Ctrl+left",
"Next bookmark":"Ctrl+right",
"Mark1 position": "Ctrl+1",
"Mark2 position": "Ctrl+2",
"Mark3 position": "Ctrl+3",
"Mark4 position": "Ctrl+4",
"Mark5 position": "Ctrl+5",
"Mark6 position": "Ctrl+6",
"Mark7 position": "Ctrl+7",
"Mark8 position": "Ctrl+8",
"Mark9 position": "Ctrl+9",
"Mark10 position": "Ctrl+0",
"close media": "Ctrl+W"
}
}

