import os

from utilities.functions import get_ir_dir

# Factory presets seeded into data/presets/audio_effects/<effect_id>/ the
# first time mpv_effect_presets.list_presets(effect_id) is called for a
# freshly-installed effect id (see _seed_defaults_if_empty there). After
# that, they're just ordinary preset files -- the user can edit or delete
# them like anything else they saved themselves.
#
# Keys must match the effect's MPVAudioFilter subclass's own
# mpv_param_map keys 1:1 (see media_core.av_play.mpv_audio_filter and the
# matching entry in mpv_effects_catalog.MPV_EFFECTS).

_ir_path = lambda name: os.path.join(get_ir_dir(), name)

DEFAULT_EFFECT_PRESETS: dict[str, list] = {
    "echo": [
        ("Slap Delay", {"in_gain": 0.7, "out_gain": 0.5, "delays": "120", "decays": "0.25"}),
        ("Hall Echo", {"in_gain": 0.6, "out_gain": 0.4, "delays": "500", "decays": "0.5"}),
        ("Long Ambient", {"in_gain": 0.5, "out_gain": 0.3, "delays": "1000", "decays": "0.6"}),
        ("Single Slapback", {"in_gain": 0.8, "out_gain": 0.6, "delays": "80", "decays": "0.3"}),
        ("Double Tap", {"in_gain": 0.7, "out_gain": 0.5, "delays": "150|300", "decays": "0.4|0.2"}),
        ("Triple Tap", {"in_gain": 0.6, "out_gain": 0.5, "delays": "120|240|360", "decays": "0.5|0.3|0.15"}),
        ("Quarter Note", {"in_gain": 0.6, "out_gain": 0.45, "delays": "500", "decays": "0.45"}),
        ("Dotted Eighth", {"in_gain": 0.6, "out_gain": 0.45, "delays": "375", "decays": "0.4"}),
        ("Ping Pong Feel", {"in_gain": 0.6, "out_gain": 0.5, "delays": "250|500", "decays": "0.5|0.35"}),
        ("Cave Echo", {"in_gain": 0.7, "out_gain": 0.6, "delays": "700|1400|2100", "decays": "0.6|0.45|0.3"}),
        ("Stadium Tail", {"in_gain": 0.8, "out_gain": 0.7, "delays": "900|1800", "decays": "0.65|0.5"}),
        ("Vintage Tape Echo", {"in_gain": 0.75, "out_gain": 0.55, "delays": "180|360|540", "decays": "0.55|0.4|0.25"}),
        ("Dub Echo", {"in_gain": 0.85, "out_gain": 0.7, "delays": "300|600|1200", "decays": "0.7|0.55|0.4"}),
        ("Slapback Vocal", {"in_gain": 0.8, "out_gain": 0.5, "delays": "110", "decays": "0.35"}),
        ("Ambient Wash", {"in_gain": 0.9, "out_gain": 0.8, "delays": "800|1600|2400", "decays": "0.7|0.6|0.5"}),
        ("Tight Room Bounce", {"in_gain": 0.6, "out_gain": 0.4, "delays": "60|120", "decays": "0.35|0.2"}),
        ("Lo-fi Repeat", {"in_gain": 0.7, "out_gain": 0.6, "delays": "400", "decays": "0.75"}),
        ("Gallop Echo", {"in_gain": 0.65, "out_gain": 0.5, "delays": "150|300|450|600", "decays": "0.5|0.4|0.3|0.2"}),
    ],
    "reverb": [
        ("Small Room", {"in_gain": 0.8, "out_gain": 0.5, "decay": 0.25, "room_size": 0.6}),
        ("Hall", {"in_gain": 0.8, "out_gain": 0.6, "decay": 0.4, "room_size": 1.0}),
        ("Vocal Booth", {"in_gain": 0.7, "out_gain": 0.35, "decay": 0.15, "room_size": 0.35}),
        ("Cathedral", {"in_gain": 0.85, "out_gain": 0.7, "decay": 0.6, "room_size": 2.2}),
        ("Bathroom Tile", {"in_gain": 0.75, "out_gain": 0.55, "decay": 0.35, "room_size": 0.5}),
        ("Living Room", {"in_gain": 0.8, "out_gain": 0.45, "decay": 0.2, "room_size": 0.7}),
        ("Concert Hall", {"in_gain": 0.85, "out_gain": 0.65, "decay": 0.5, "room_size": 1.6}),
        ("Recording Studio", {"in_gain": 0.7, "out_gain": 0.3, "decay": 0.1, "room_size": 0.4}),
        ("Warehouse", {"in_gain": 0.85, "out_gain": 0.7, "decay": 0.55, "room_size": 2.8}),
        ("Stairwell", {"in_gain": 0.8, "out_gain": 0.6, "decay": 0.45, "room_size": 1.3}),
        ("Chapel", {"in_gain": 0.85, "out_gain": 0.7, "decay": 0.55, "room_size": 1.9}),
        ("Underground Garage", {"in_gain": 0.8, "out_gain": 0.6, "decay": 0.4, "room_size": 1.1}),
        ("Dry Slight Air", {"in_gain": 0.7, "out_gain": 0.25, "decay": 0.08, "room_size": 0.3}),
        ("Ambient Space", {"in_gain": 0.9, "out_gain": 0.8, "decay": 0.75, "room_size": 3.5}),
        ("Drum Room", {"in_gain": 0.8, "out_gain": 0.5, "decay": 0.3, "room_size": 0.9}),
        ("Plate Style", {"in_gain": 0.75, "out_gain": 0.5, "decay": 0.35, "room_size": 0.8}),
        ("Tunnel", {"in_gain": 0.85, "out_gain": 0.75, "decay": 0.65, "room_size": 2.5}),
        ("Gymnasium", {"in_gain": 0.85, "out_gain": 0.7, "decay": 0.6, "room_size": 3.0}),
        ("Whisper Chamber", {"in_gain": 0.7, "out_gain": 0.4, "decay": 0.25, "room_size": 0.55}),
        ("Cavern", {"in_gain": 0.9, "out_gain": 0.85, "decay": 0.8, "room_size": 4.5}),
    ],
    "convolution_reverb": [
        ("Small Speaker (Close)", {"impulse_response_path": _ir_path("Small-Speaker1.wav"), "dry": 1.0, "wet": 0.6}),
        ("Small Speaker (Distant)", {"impulse_response_path": _ir_path("Small-Speaker3.wav"), "dry": 0.8, "wet": 0.9}),
        ("Car Interior", {"impulse_response_path": _ir_path("car1.wav"), "dry": 1.0, "wet": 0.7}),
        ("Car Interior (Alt)", {"impulse_response_path": _ir_path("car2.wav"), "dry": 1.0, "wet": 0.7}),
        ("Speaker Subtle", {"impulse_response_path": _ir_path("Small-Speaker2.wav"), "dry": 1.0, "wet": 0.4}),
        ("Speaker Warm", {"impulse_response_path": _ir_path("Small-Speaker4.wav"), "dry": 0.9, "wet": 0.8}),
        ("Speaker Bright", {"impulse_response_path": _ir_path("Small-Speaker5.wav"), "dry": 0.9, "wet": 0.9}),
        ("Car Cabin Dry", {"impulse_response_path": _ir_path("car1.wav"), "dry": 1.2, "wet": 0.4}),
        ("Car Cabin Wet", {"impulse_response_path": _ir_path("car2.wav"), "dry": 0.7, "wet": 1.1}),
        ("Radio Speaker", {"impulse_response_path": _ir_path("Small-Speaker1.wav"), "dry": 0.8, "wet": 1.2}),
        ("Vintage Radio", {"impulse_response_path": _ir_path("Small-Speaker3.wav"), "dry": 0.7, "wet": 1.3}),
        ("Studio Monitor", {"impulse_response_path": _ir_path("Small-Speaker4.wav"), "dry": 1.1, "wet": 0.5}),
        ("Portable Speaker", {"impulse_response_path": _ir_path("Small-Speaker5.wav"), "dry": 1.0, "wet": 0.7}),
        ("Hatchback", {"impulse_response_path": _ir_path("car1.wav"), "dry": 0.9, "wet": 0.9}),
        ("Sedan Cabin", {"impulse_response_path": _ir_path("car2.wav"), "dry": 1.0, "wet": 0.8}),
        ("Compact Speaker", {"impulse_response_path": _ir_path("Small-Speaker2.wav"), "dry": 1.0, "wet": 0.6}),
        ("Loud Speaker", {"impulse_response_path": _ir_path("Small-Speaker1.wav"), "dry": 0.9, "wet": 1.0}),
        ("Deep Cabin", {"impulse_response_path": _ir_path("car1.wav"), "dry": 0.8, "wet": 1.0}),
    ],
    "lowpass": [
        ("Telephone", {"frequency": 3000.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Muffled / Next Room", {"frequency": 800.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Gentle Air Roll-off", {"frequency": 12000.0, "poles": 1, "width": 0.707, "mix": 1.0}),
        ("AM Radio", {"frequency": 2500.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Underwater", {"frequency": 400.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Warm Vinyl", {"frequency": 7000.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Lo-fi Crush", {"frequency": 2000.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Soft Blanket", {"frequency": 5000.0, "poles": 1, "width": 0.707, "mix": 1.0}),
        ("Sub Only", {"frequency": 150.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Bass Pass", {"frequency": 300.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Dark Warmth", {"frequency": 4000.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Old Recording", {"frequency": 6000.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Wall Muffle", {"frequency": 1000.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Gentle Top Cut", {"frequency": 15000.0, "poles": 1, "width": 0.707, "mix": 1.0}),
        ("Half Mix Muffle", {"frequency": 2000.0, "poles": 2, "width": 0.707, "mix": 0.5}),
        ("Distant Thunder", {"frequency": 250.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Cassette Tape", {"frequency": 9000.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("FM Broadcast", {"frequency": 15000.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Megaphone Tail", {"frequency": 3500.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Deep Muffle", {"frequency": 600.0, "poles": 2, "width": 0.707, "mix": 1.0}),
    ],
    "highpass": [
        ("Remove Rumble", {"frequency": 80.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Thin/Radio Voice", {"frequency": 500.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Tighten Bass Bleed", {"frequency": 150.0, "poles": 1, "width": 0.707, "mix": 1.0}),
        ("Clean Lows", {"frequency": 40.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Telephone Thin", {"frequency": 300.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Vocal Clarity", {"frequency": 120.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Lo-fi Thin", {"frequency": 800.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Nasal Radio", {"frequency": 1000.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Wind Cut", {"frequency": 200.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Podcast Voice", {"frequency": 100.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Crisp Top Only", {"frequency": 2000.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Mic Handling Cut", {"frequency": 60.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Stage Vocal", {"frequency": 150.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Acoustic Guitar", {"frequency": 90.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Speech Band", {"frequency": 400.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Intercom", {"frequency": 600.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Gentle Cleanup", {"frequency": 30.0, "poles": 1, "width": 0.707, "mix": 1.0}),
        ("Aggressive Thin", {"frequency": 1500.0, "poles": 2, "width": 0.707, "mix": 1.0}),
        ("Half Mix Thin", {"frequency": 500.0, "poles": 2, "width": 0.707, "mix": 0.5}),
        ("Sub Rumble Kill", {"frequency": 50.0, "poles": 2, "width": 0.707, "mix": 1.0}),
    ],
    "bandpass": [
        ("Old Radio", {"frequency": 1800.0, "width": 1500.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Telephone Voice", {"frequency": 1500.0, "width": 2000.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Megaphone", {"frequency": 1200.0, "width": 1000.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Intercom", {"frequency": 1000.0, "width": 1200.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Walkie Talkie", {"frequency": 1400.0, "width": 1800.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("AM Band", {"frequency": 2000.0, "width": 2500.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Narrow Band", {"frequency": 800.0, "width": 400.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Wide Band", {"frequency": 2500.0, "width": 5000.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Vocal Presence", {"frequency": 2200.0, "width": 3000.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Snare Body", {"frequency": 250.0, "width": 500.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Kick Punch", {"frequency": 80.0, "width": 120.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Cymbal Sizzle", {"frequency": 8000.0, "width": 6000.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Mid Focus", {"frequency": 1000.0, "width": 800.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Tinny Speaker", {"frequency": 1600.0, "width": 900.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Underwater Voice", {"frequency": 600.0, "width": 500.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Robot Voice", {"frequency": 900.0, "width": 300.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Half Mix Band", {"frequency": 1500.0, "width": 2000.0, "csg": 0, "mix": 0.5, "width_type": "h"}),
        ("Constant Skirt", {"frequency": 1500.0, "width": 2000.0, "csg": 1, "mix": 1.0, "width_type": "h"}),
        ("Speech Isolation", {"frequency": 1700.0, "width": 1600.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
        ("Vintage Phone", {"frequency": 1300.0, "width": 1400.0, "csg": 0, "mix": 1.0, "width_type": "h"}),
    ],
    "bandreject": [
        ("Notch Hum (60Hz)", {"frequency": 60.0, "width_type": "h", "width": 10.0, "mix": 1.0}),
        ("Notch Hum (50Hz)", {"frequency": 50.0, "width_type": "h", "width": 10.0, "mix": 1.0}),
        ("Scoop Mids", {"frequency": 1000.0, "width_type": "o", "width": 1.0, "mix": 1.0}),
        ("Kill Whine (8kHz)", {"frequency": 8000.0, "width_type": "h", "width": 200.0, "mix": 1.0}),
        ("Harmonic Hum 120Hz", {"frequency": 120.0, "width_type": "h", "width": 15.0, "mix": 1.0}),
        ("Harmonic Hum 100Hz", {"frequency": 100.0, "width_type": "h", "width": 15.0, "mix": 1.0}),
        ("Sibilance Cut", {"frequency": 7000.0, "width_type": "o", "width": 1.5, "mix": 1.0}),
        ("Boxy Resonance", {"frequency": 400.0, "width_type": "o", "width": 2.0, "mix": 1.0}),
        ("Honky Tone", {"frequency": 900.0, "width_type": "o", "width": 1.5, "mix": 1.0}),
        ("Camera Whine", {"frequency": 15734.0, "width_type": "h", "width": 500.0, "mix": 1.0}),
        ("Fluorescent Buzz", {"frequency": 180.0, "width_type": "h", "width": 20.0, "mix": 1.0}),
        ("Narrow Notch 1k", {"frequency": 1000.0, "width_type": "h", "width": 30.0, "mix": 1.0}),
        ("Wide Mid Cut", {"frequency": 800.0, "width_type": "o", "width": 3.0, "mix": 1.0}),
        ("Feedback Killer 2k", {"frequency": 2000.0, "width_type": "h", "width": 100.0, "mix": 1.0}),
        ("Feedback Killer 4k", {"frequency": 4000.0, "width_type": "h", "width": 150.0, "mix": 1.0}),
        ("Hiss Region Cut", {"frequency": 10000.0, "width_type": "o", "width": 1.0, "mix": 1.0}),
        ("Mud Removal", {"frequency": 250.0, "width_type": "o", "width": 1.5, "mix": 1.0}),
        ("Half Mix Notch", {"frequency": 1000.0, "width_type": "o", "width": 1.0, "mix": 0.5}),
        ("Transformer Hum", {"frequency": 240.0, "width_type": "h", "width": 25.0, "mix": 1.0}),
        ("Nasal Cut", {"frequency": 1100.0, "width_type": "o", "width": 1.2, "mix": 1.0}),
    ],
    "bass": [
        ("Warm Boost", {"gain": 4.0, "frequency": 100.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Tight Cut", {"gain": -4.0, "frequency": 120.0, "width_type": "q", "width": 0.7, "poles": 2, "mix": 1.0}),
        ("Subwoofer Boost", {"gain": 6.0, "frequency": 60.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Gentle Warmth", {"gain": 2.0, "frequency": 120.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Deep Rumble", {"gain": 8.0, "frequency": 50.0, "width_type": "q", "width": 0.4, "poles": 2, "mix": 1.0}),
        ("Bass Roll-off", {"gain": -6.0, "frequency": 80.0, "width_type": "q", "width": 0.6, "poles": 2, "mix": 1.0}),
        ("Punchy Low", {"gain": 5.0, "frequency": 90.0, "width_type": "q", "width": 0.8, "poles": 2, "mix": 1.0}),
        ("Mud Cleanup", {"gain": -3.0, "frequency": 200.0, "width_type": "q", "width": 0.7, "poles": 2, "mix": 1.0}),
        ("Vintage Warm", {"gain": 3.5, "frequency": 110.0, "width_type": "q", "width": 0.6, "poles": 2, "mix": 1.0}),
        ("Hip-hop Weight", {"gain": 7.0, "frequency": 70.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Acoustic Body", {"gain": 3.0, "frequency": 140.0, "width_type": "q", "width": 0.6, "poles": 2, "mix": 1.0}),
        ("Thin Out", {"gain": -8.0, "frequency": 150.0, "width_type": "q", "width": 0.7, "poles": 2, "mix": 1.0}),
        ("Sub Rumble Cut", {"gain": -5.0, "frequency": 45.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Loudness Bass", {"gain": 6.0, "frequency": 100.0, "width_type": "q", "width": 0.7, "poles": 2, "mix": 1.0}),
        ("Half Mix Warm", {"gain": 4.0, "frequency": 100.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 0.5}),
        ("Bass Shelf Up", {"gain": 5.0, "frequency": 200.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Bass Shelf Down", {"gain": -5.0, "frequency": 200.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Club Low End", {"gain": 9.0, "frequency": 65.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Soft Low Shelf", {"gain": 2.5, "frequency": 160.0, "width_type": "q", "width": 0.5, "poles": 1, "mix": 1.0}),
        ("Boomy Fix", {"gain": -4.5, "frequency": 90.0, "width_type": "q", "width": 1.0, "poles": 2, "mix": 1.0}),
    ],
    "treble": [
        ("Bright/Airy", {"gain": 4.0, "frequency": 8000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("De-harsh", {"gain": -3.0, "frequency": 6000.0, "width_type": "q", "width": 0.7, "poles": 2, "mix": 1.0}),
        ("Sparkle Boost", {"gain": 6.0, "frequency": 10000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Sibilance Tame", {"gain": -4.0, "frequency": 7500.0, "width_type": "q", "width": 0.8, "poles": 2, "mix": 1.0}),
        ("Gentle Sheen", {"gain": 2.0, "frequency": 9000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Dull Down", {"gain": -6.0, "frequency": 8000.0, "width_type": "q", "width": 0.6, "poles": 2, "mix": 1.0}),
        ("Presence Lift", {"gain": 3.0, "frequency": 5000.0, "width_type": "q", "width": 0.6, "poles": 2, "mix": 1.0}),
        ("Cymbal Air", {"gain": 5.0, "frequency": 12000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Harsh Fix", {"gain": -5.0, "frequency": 4000.0, "width_type": "q", "width": 0.8, "poles": 2, "mix": 1.0}),
        ("Vintage Dark", {"gain": -4.0, "frequency": 6000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Crisp Detail", {"gain": 4.5, "frequency": 9000.0, "width_type": "q", "width": 0.7, "poles": 2, "mix": 1.0}),
        ("Smooth Top", {"gain": -2.0, "frequency": 10000.0, "width_type": "q", "width": 0.5, "poles": 1, "mix": 1.0}),
        ("Vocal Air", {"gain": 3.5, "frequency": 11000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Tame Bright Strings", {"gain": -3.5, "frequency": 5500.0, "width_type": "q", "width": 0.7, "poles": 2, "mix": 1.0}),
        ("Half Mix Bright", {"gain": 4.0, "frequency": 8000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 0.5}),
        ("Treble Shelf Up", {"gain": 5.0, "frequency": 4000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Treble Shelf Down", {"gain": -5.0, "frequency": 4000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Hi-fi Detail", {"gain": 2.5, "frequency": 13000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Fatigue Relief", {"gain": -4.5, "frequency": 8500.0, "width_type": "q", "width": 1.0, "poles": 2, "mix": 1.0}),
        ("Open Air", {"gain": 7.0, "frequency": 14000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
    ],
    "tiltshelf": [
        ("Warmer Overall", {"gain": -3.0, "frequency": 3000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Brighter Overall", {"gain": 3.0, "frequency": 3000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Much Warmer", {"gain": -6.0, "frequency": 2500.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Much Brighter", {"gain": 6.0, "frequency": 2500.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Slight Warm", {"gain": -1.5, "frequency": 3500.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Slight Bright", {"gain": 1.5, "frequency": 3500.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Lo-fi Tilt", {"gain": -8.0, "frequency": 2000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Hi-fi Tilt", {"gain": 8.0, "frequency": 2000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Vintage Radio Tilt", {"gain": -5.0, "frequency": 1500.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Modern Sheen", {"gain": 5.0, "frequency": 4000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Analog Warmth", {"gain": -4.0, "frequency": 3000.0, "width_type": "q", "width": 0.6, "poles": 2, "mix": 1.0}),
        ("Digital Clarity", {"gain": 4.0, "frequency": 3000.0, "width_type": "q", "width": 0.6, "poles": 2, "mix": 1.0}),
        ("Night Listening", {"gain": -2.5, "frequency": 3000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Daytime Detail", {"gain": 2.5, "frequency": 3000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Half Mix Warm", {"gain": -3.0, "frequency": 3000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 0.5}),
        ("Half Mix Bright", {"gain": 3.0, "frequency": 3000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 0.5}),
        ("Podcast Warm", {"gain": -2.0, "frequency": 4000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Podcast Crisp", {"gain": 2.0, "frequency": 4000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Extreme Dark", {"gain": -10.0, "frequency": 2000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
        ("Extreme Bright", {"gain": 10.0, "frequency": 2000.0, "width_type": "q", "width": 0.5, "poles": 2, "mix": 1.0}),
    ],
    "compressor": [
        ("Gentle", {"level_in": 1.0, "threshold": 0.35, "ratio": 2.0, "attack": 20.0, "release": 250.0,
                     "makeup": 1.2, "knee": 2.82843, "detection": "rms", "mix": 1.0}),
        ("Podcast Voice", {"level_in": 1.0, "threshold": 0.15, "ratio": 4.0, "attack": 10.0, "release": 180.0,
                            "makeup": 1.6, "knee": 2.82843, "detection": "rms", "mix": 1.0}),
        ("Broadcast Limiting", {"level_in": 1.0, "threshold": 0.09, "ratio": 8.0, "attack": 5.0, "release": 120.0,
                                 "makeup": 2.0, "knee": 1.5, "detection": "peak", "mix": 1.0}),
        ("Drum Smash", {"level_in": 1.0, "threshold": 0.08, "ratio": 10.0, "attack": 2.0, "release": 80.0,
                         "makeup": 2.5, "knee": 1.0, "detection": "peak", "mix": 1.0}),
        ("Vocal Leveler", {"level_in": 1.0, "threshold": 0.2, "ratio": 3.0, "attack": 15.0, "release": 200.0,
                            "makeup": 1.4, "knee": 3.0, "detection": "rms", "mix": 1.0}),
        ("Bus Glue", {"level_in": 1.0, "threshold": 0.3, "ratio": 2.0, "attack": 30.0, "release": 300.0,
                       "makeup": 1.1, "knee": 4.0, "detection": "rms", "mix": 1.0}),
        ("Punch Drums", {"level_in": 1.0, "threshold": 0.25, "ratio": 4.0, "attack": 25.0, "release": 150.0,
                          "makeup": 1.3, "knee": 2.0, "detection": "peak", "mix": 1.0}),
        ("Bass Control", {"level_in": 1.0, "threshold": 0.18, "ratio": 5.0, "attack": 20.0, "release": 250.0,
                           "makeup": 1.5, "knee": 2.5, "detection": "rms", "mix": 1.0}),
        ("Parallel Crush", {"level_in": 1.0, "threshold": 0.05, "ratio": 20.0, "attack": 1.0, "release": 50.0,
                             "makeup": 1.0, "knee": 1.0, "detection": "peak", "mix": 0.4}),
        ("Acoustic Guitar", {"level_in": 1.0, "threshold": 0.28, "ratio": 2.5, "attack": 20.0, "release": 300.0,
                              "makeup": 1.2, "knee": 3.0, "detection": "rms", "mix": 1.0}),
        ("Snare Snap", {"level_in": 1.0, "threshold": 0.15, "ratio": 6.0, "attack": 5.0, "release": 100.0,
                         "makeup": 1.8, "knee": 1.5, "detection": "peak", "mix": 1.0}),
        ("Gentle Master", {"level_in": 1.0, "threshold": 0.4, "ratio": 1.5, "attack": 50.0, "release": 400.0,
                            "makeup": 1.05, "knee": 5.0, "detection": "rms", "mix": 1.0}),
        ("Loud Master", {"level_in": 1.0, "threshold": 0.12, "ratio": 4.0, "attack": 10.0, "release": 150.0,
                          "makeup": 2.2, "knee": 2.0, "detection": "rms", "mix": 1.0}),
        ("De-pump Voice", {"level_in": 1.0, "threshold": 0.22, "ratio": 3.0, "attack": 5.0, "release": 500.0,
                            "makeup": 1.3, "knee": 4.0, "detection": "rms", "mix": 1.0}),
        ("Half Mix Comp", {"level_in": 1.0, "threshold": 0.2, "ratio": 3.0, "attack": 15.0, "release": 200.0,
                            "makeup": 1.3, "knee": 2.82843, "detection": "rms", "mix": 0.5}),
        ("Fast Peak Catch", {"level_in": 1.0, "threshold": 0.1, "ratio": 12.0, "attack": 0.5, "release": 60.0,
                              "makeup": 1.5, "knee": 1.0, "detection": "peak", "mix": 1.0}),
        ("Ambient Sustain", {"level_in": 1.0, "threshold": 0.3, "ratio": 2.5, "attack": 40.0, "release": 600.0,
                              "makeup": 1.4, "knee": 4.0, "detection": "rms", "mix": 1.0}),
        ("Rap Vocal", {"level_in": 1.0, "threshold": 0.13, "ratio": 6.0, "attack": 8.0, "release": 120.0,
                        "makeup": 1.9, "knee": 2.0, "detection": "peak", "mix": 1.0}),
        ("Soft Knee Smooth", {"level_in": 1.0, "threshold": 0.3, "ratio": 3.0, "attack": 20.0, "release": 250.0,
                               "makeup": 1.3, "knee": 8.0, "detection": "rms", "mix": 1.0}),
        ("Hard Knee Control", {"level_in": 1.0, "threshold": 0.15, "ratio": 5.0, "attack": 10.0, "release": 150.0,
                                "makeup": 1.6, "knee": 1.0, "detection": "peak", "mix": 1.0}),
    ],
    "limiter": [
        ("Transparent", {"level_in": 1.0, "level_out": 1.0, "limit": 0.95, "attack": 5.0, "release": 50.0,
                          "asc": "true", "asc_level": 0.5, "level": "true"}),
        ("Loud/Streaming-Safe", {"level_in": 1.0, "level_out": 1.0, "limit": 0.89, "attack": 2.0, "release": 100.0,
                                  "asc": "true", "asc_level": 0.7, "level": "true"}),
        ("Brick Wall", {"level_in": 1.0, "level_out": 1.0, "limit": 0.98, "attack": 0.5, "release": 30.0,
                         "asc": "false", "asc_level": 0.5, "level": "true"}),
        ("Gentle Ceiling", {"level_in": 1.0, "level_out": 1.0, "limit": 0.85, "attack": 10.0, "release": 200.0,
                             "asc": "true", "asc_level": 0.3, "level": "true"}),
        ("Master Bus", {"level_in": 1.0, "level_out": 1.0, "limit": 0.92, "attack": 3.0, "release": 80.0,
                         "asc": "true", "asc_level": 0.6, "level": "true"}),
        ("Loudness Push", {"level_in": 1.5, "level_out": 1.0, "limit": 0.9, "attack": 1.0, "release": 50.0,
                            "asc": "true", "asc_level": 0.8, "level": "true"}),
        ("Peak Safety", {"level_in": 1.0, "level_out": 1.0, "limit": 0.99, "attack": 1.0, "release": 20.0,
                          "asc": "false", "asc_level": 0.5, "level": "false"}),
        ("Broadcast Standard", {"level_in": 1.0, "level_out": 1.0, "limit": 0.79, "attack": 2.0, "release": 100.0,
                                 "asc": "true", "asc_level": 0.7, "level": "true"}),
        ("Podcast Final", {"level_in": 1.0, "level_out": 1.0, "limit": 0.85, "attack": 3.0, "release": 70.0,
                            "asc": "true", "asc_level": 0.6, "level": "true"}),
        ("Drum Bus Limit", {"level_in": 1.0, "level_out": 1.0, "limit": 0.88, "attack": 1.0, "release": 40.0,
                             "asc": "true", "asc_level": 0.9, "level": "true"}),
        ("Vocal Ride", {"level_in": 1.0, "level_out": 1.0, "limit": 0.9, "attack": 5.0, "release": 150.0,
                         "asc": "true", "asc_level": 0.4, "level": "true"}),
        ("Bass Guard", {"level_in": 1.0, "level_out": 1.0, "limit": 0.87, "attack": 8.0, "release": 250.0,
                         "asc": "true", "asc_level": 0.5, "level": "true"}),
        ("Night Mode", {"level_in": 1.0, "level_out": 1.0, "limit": 0.7, "attack": 10.0, "release": 300.0,
                         "asc": "true", "asc_level": 0.3, "level": "true"}),
        ("Max Loud", {"level_in": 2.0, "level_out": 1.0, "limit": 0.95, "attack": 0.5, "release": 30.0,
                       "asc": "true", "asc_level": 1.0, "level": "true"}),
        ("Half Mix Limit", {"level_in": 1.0, "level_out": 1.0, "limit": 0.9, "attack": 5.0, "release": 50.0,
                             "asc": "true", "asc_level": 0.5, "level": "true"}),
        ("No Auto Level", {"level_in": 1.0, "level_out": 1.0, "limit": 0.9, "attack": 5.0, "release": 50.0,
                            "asc": "true", "asc_level": 0.5, "level": "false"}),
        ("Slow Release", {"level_in": 1.0, "level_out": 1.0, "limit": 0.9, "attack": 5.0, "release": 500.0,
                           "asc": "true", "asc_level": 0.5, "level": "true"}),
        ("Fast Attack", {"level_in": 1.0, "level_out": 1.0, "limit": 0.9, "attack": 0.1, "release": 50.0,
                          "asc": "false", "asc_level": 0.5, "level": "true"}),
        ("Clipping Guard", {"level_in": 1.0, "level_out": 1.0, "limit": 0.96, "attack": 0.1, "release": 10.0,
                             "asc": "false", "asc_level": 0.5, "level": "true"}),
        ("Soft Touch", {"level_in": 1.0, "level_out": 1.0, "limit": 0.93, "attack": 15.0, "release": 400.0,
                         "asc": "true", "asc_level": 0.2, "level": "true"}),
    ],
    "gate": [
        ("Noise Gate (Vocal)", {"level_in": 1.0, "mode": "downward", "range": 0.02, "threshold": 0.08,
                                 "ratio": 4.0, "attack": 5.0, "release": 150.0, "makeup": 1.0,
                                 "knee": 2.828427125, "detection": "rms", "link": "average"}),
        ("Aggressive Gate", {"level_in": 1.0, "mode": "downward", "range": 0.0, "threshold": 0.15,
                              "ratio": 8.0, "attack": 2.0, "release": 80.0, "makeup": 1.0,
                              "knee": 1.0, "detection": "peak", "link": "average"}),
        ("Drum Gate Kick", {"level_in": 1.0, "mode": "downward", "range": 0.01, "threshold": 0.2,
                             "ratio": 10.0, "attack": 1.0, "release": 50.0, "makeup": 1.0,
                             "knee": 1.0, "detection": "peak", "link": "average"}),
        ("Gentle Hiss Gate", {"level_in": 1.0, "mode": "downward", "range": 0.1, "threshold": 0.03,
                               "ratio": 2.0, "attack": 10.0, "release": 300.0, "makeup": 1.0,
                               "knee": 4.0, "detection": "rms", "link": "average"}),
        ("Room Noise Cut", {"level_in": 1.0, "mode": "downward", "range": 0.05, "threshold": 0.05,
                             "ratio": 3.0, "attack": 5.0, "release": 200.0, "makeup": 1.0,
                             "knee": 2.0, "detection": "rms", "link": "average"}),
        ("Snare Gate", {"level_in": 1.0, "mode": "downward", "range": 0.02, "threshold": 0.12,
                         "ratio": 6.0, "attack": 1.0, "release": 100.0, "makeup": 1.0,
                         "knee": 1.5, "detection": "peak", "link": "average"}),
        ("Tom Gate", {"level_in": 1.0, "mode": "downward", "range": 0.02, "threshold": 0.15,
                       "ratio": 8.0, "attack": 2.0, "release": 150.0, "makeup": 1.0,
                       "knee": 1.0, "detection": "peak", "link": "average"}),
        ("Hi-hat Gate", {"level_in": 1.0, "mode": "downward", "range": 0.03, "threshold": 0.06,
                          "ratio": 4.0, "attack": 1.0, "release": 30.0, "makeup": 1.0,
                          "knee": 2.0, "detection": "peak", "link": "average"}),
        ("Upward Expander", {"level_in": 1.0, "mode": "upward", "range": 0.5, "threshold": 0.1,
                              "ratio": 2.0, "attack": 5.0, "release": 200.0, "makeup": 1.0,
                              "knee": 2.0, "detection": "rms", "link": "average"}),
        ("Speech Cleanup", {"level_in": 1.0, "mode": "downward", "range": 0.03, "threshold": 0.07,
                             "ratio": 5.0, "attack": 3.0, "release": 120.0, "makeup": 1.0,
                             "knee": 2.5, "detection": "rms", "link": "average"}),
        ("Guitar Amp Gate", {"level_in": 1.0, "mode": "downward", "range": 0.01, "threshold": 0.1,
                              "ratio": 8.0, "attack": 1.0, "release": 60.0, "makeup": 1.0,
                              "knee": 1.0, "detection": "peak", "link": "average"}),
        ("Max Link Gate", {"level_in": 1.0, "mode": "downward", "range": 0.02, "threshold": 0.1,
                            "ratio": 4.0, "attack": 5.0, "release": 150.0, "makeup": 1.0,
                            "knee": 2.828427125, "detection": "rms", "link": "maximum"}),
        ("Slow Release Gate", {"level_in": 1.0, "mode": "downward", "range": 0.05, "threshold": 0.08,
                                "ratio": 3.0, "attack": 10.0, "release": 500.0, "makeup": 1.0,
                                "knee": 3.0, "detection": "rms", "link": "average"}),
        ("Fast Attack Gate", {"level_in": 1.0, "mode": "downward", "range": 0.02, "threshold": 0.1,
                               "ratio": 6.0, "attack": 0.5, "release": 100.0, "makeup": 1.0,
                               "knee": 1.0, "detection": "peak", "link": "average"}),
        ("Half Mix Gate", {"level_in": 1.0, "mode": "downward", "range": 0.05, "threshold": 0.08,
                            "ratio": 4.0, "attack": 5.0, "release": 150.0, "makeup": 1.0,
                            "knee": 2.828427125, "detection": "rms", "link": "average"}),
        ("Deep Silence", {"level_in": 1.0, "mode": "downward", "range": 0.0, "threshold": 0.05,
                           "ratio": 20.0, "attack": 1.0, "release": 50.0, "makeup": 1.0,
                           "knee": 1.0, "detection": "rms", "link": "average"}),
        ("Bass Gate", {"level_in": 1.0, "mode": "downward", "range": 0.03, "threshold": 0.12,
                        "ratio": 5.0, "attack": 10.0, "release": 250.0, "makeup": 1.0,
                        "knee": 2.0, "detection": "rms", "link": "average"}),
        ("Vocal Breath Cut", {"level_in": 1.0, "mode": "downward", "range": 0.08, "threshold": 0.04,
                               "ratio": 3.0, "attack": 20.0, "release": 400.0, "makeup": 1.0,
                               "knee": 4.0, "detection": "rms", "link": "average"}),
        ("Field Recording", {"level_in": 1.0, "mode": "downward", "range": 0.06, "threshold": 0.02,
                              "ratio": 2.5, "attack": 15.0, "release": 350.0, "makeup": 1.0,
                              "knee": 3.5, "detection": "rms", "link": "average"}),
        ("Hard Floor", {"level_in": 1.0, "mode": "downward", "range": 0.0, "threshold": 0.18,
                         "ratio": 15.0, "attack": 1.0, "release": 40.0, "makeup": 1.0,
                         "knee": 1.0, "detection": "peak", "link": "average"}),
    ],
    "dynaudnorm": [
        ("Podcast Leveling", {"framelen": 500, "gausssize": 31, "peak": 0.95, "maxgain": 10.0,
                               "targetrms": 0.3, "compress": 0.0}),
        ("Music Loudness Match", {"framelen": 500, "gausssize": 15, "peak": 0.95, "maxgain": 6.0,
                                   "targetrms": 0.0, "compress": 0.0}),
        ("Movie Dialogue", {"framelen": 1000, "gausssize": 31, "peak": 0.9, "maxgain": 15.0,
                            "targetrms": 0.2, "compress": 0.0}),
        ("Quiet Source Boost", {"framelen": 500, "gausssize": 31, "peak": 0.95, "maxgain": 30.0,
                                 "targetrms": 0.0, "compress": 0.0}),
        ("Gentle Leveling", {"framelen": 500, "gausssize": 31, "peak": 0.95, "maxgain": 3.0,
                              "targetrms": 0.0, "compress": 0.0}),
        ("Night Mode", {"framelen": 1000, "gausssize": 51, "peak": 0.8, "maxgain": 20.0,
                         "targetrms": 0.1, "compress": 0.3}),
        ("Interview Cleanup", {"framelen": 800, "gausssize": 31, "peak": 0.95, "maxgain": 12.0,
                                "targetrms": 0.25, "compress": 0.1}),
        ("Live Recording", {"framelen": 500, "gausssize": 21, "peak": 0.95, "maxgain": 8.0,
                             "targetrms": 0.0, "compress": 0.0}),
        ("Audiobook", {"framelen": 1000, "gausssize": 31, "peak": 0.9, "maxgain": 18.0,
                        "targetrms": 0.3, "compress": 0.2}),
        ("Fast Adaptive", {"framelen": 100, "gausssize": 11, "peak": 0.95, "maxgain": 10.0,
                            "targetrms": 0.0, "compress": 0.0}),
        ("Slow Adaptive", {"framelen": 2000, "gausssize": 61, "peak": 0.95, "maxgain": 10.0,
                            "targetrms": 0.0, "compress": 0.0}),
        ("Compressed Radio", {"framelen": 500, "gausssize": 31, "peak": 0.9, "maxgain": 10.0,
                               "targetrms": 0.2, "compress": 0.5}),
        ("Heavy Compression", {"framelen": 500, "gausssize": 31, "peak": 0.85, "maxgain": 10.0,
                                "targetrms": 0.3, "compress": 1.0}),
        ("TV Normalize", {"framelen": 500, "gausssize": 31, "peak": 0.89, "maxgain": 10.0,
                           "targetrms": 0.0, "compress": 0.0}),
        ("Concert Film", {"framelen": 1000, "gausssize": 41, "peak": 0.92, "maxgain": 12.0,
                           "targetrms": 0.15, "compress": 0.1}),
        ("Voice Memo Boost", {"framelen": 500, "gausssize": 31, "peak": 0.95, "maxgain": 50.0,
                               "targetrms": 0.0, "compress": 0.0}),
        ("Streaming Level", {"framelen": 500, "gausssize": 31, "peak": 0.89, "maxgain": 8.0,
                              "targetrms": 0.1, "compress": 0.0}),
        ("Wide Window", {"framelen": 5000, "gausssize": 101, "peak": 0.95, "maxgain": 10.0,
                          "targetrms": 0.0, "compress": 0.0}),
        ("Narrow Window", {"framelen": 50, "gausssize": 5, "peak": 0.95, "maxgain": 10.0,
                            "targetrms": 0.0, "compress": 0.0}),
        ("Balanced Default+", {"framelen": 500, "gausssize": 31, "peak": 0.95, "maxgain": 10.0,
                                "targetrms": 0.15, "compress": 0.05}),
    ],
    "speechnorm": [
        ("Weak/Slow", {"peak": 0.95, "expansion": 3.0, "compression": 2.0, "threshold": 0.0, "raise": 0.00001, "fall": 0.00001}),
        ("Strong/Fast (Podcast)", {"peak": 0.95, "expansion": 12.5, "compression": 2.0, "threshold": 0.0, "raise": 0.0001, "fall": 0.0001}),
        ("Whisper Boost", {"peak": 0.95, "expansion": 25.0, "compression": 2.0, "threshold": 0.0, "raise": 0.0005, "fall": 0.0005}),
        ("Gentle Lift", {"peak": 0.9, "expansion": 2.0, "compression": 2.0, "threshold": 0.0, "raise": 0.00001, "fall": 0.00001}),
        ("Interview Voice", {"peak": 0.95, "expansion": 8.0, "compression": 2.0, "threshold": 0.0, "raise": 0.00005, "fall": 0.00005}),
        ("Lecture Voice", {"peak": 0.95, "expansion": 10.0, "compression": 3.0, "threshold": 0.0, "raise": 0.0001, "fall": 0.0001}),
        ("Quiet Phone Call", {"peak": 0.95, "expansion": 20.0, "compression": 2.5, "threshold": 0.0, "raise": 0.0003, "fall": 0.0003}),
        ("Distant Speaker", {"peak": 0.95, "expansion": 15.0, "compression": 2.0, "threshold": 0.0, "raise": 0.0002, "fall": 0.0002}),
        ("Soft Dialogue", {"peak": 0.9, "expansion": 6.0, "compression": 2.0, "threshold": 0.0, "raise": 0.00003, "fall": 0.00003}),
        ("Max Expansion", {"peak": 0.95, "expansion": 50.0, "compression": 2.0, "threshold": 0.0, "raise": 0.001, "fall": 0.001}),
        ("Balanced Speech", {"peak": 0.95, "expansion": 5.0, "compression": 2.0, "threshold": 0.0, "raise": 0.00003, "fall": 0.00003}),
        ("Fast Raise", {"peak": 0.95, "expansion": 10.0, "compression": 2.0, "threshold": 0.0, "raise": 0.001, "fall": 0.0001}),
        ("Fast Fall", {"peak": 0.95, "expansion": 10.0, "compression": 2.0, "threshold": 0.0, "raise": 0.0001, "fall": 0.001}),
        ("Both Fast", {"peak": 0.95, "expansion": 10.0, "compression": 2.0, "threshold": 0.0, "raise": 0.001, "fall": 0.001}),
        ("Both Slow", {"peak": 0.95, "expansion": 10.0, "compression": 2.0, "threshold": 0.0, "raise": 0.000001, "fall": 0.000001}),
        ("With Threshold", {"peak": 0.95, "expansion": 10.0, "compression": 2.0, "threshold": 0.1, "raise": 0.0001, "fall": 0.0001}),
        ("Half Mix Speech", {"peak": 0.95, "expansion": 10.0, "compression": 2.0, "threshold": 0.0, "raise": 0.0001, "fall": 0.0001}),
        ("Audiobook Voice", {"peak": 0.92, "expansion": 7.0, "compression": 2.0, "threshold": 0.0, "raise": 0.00005, "fall": 0.00005}),
        ("Conference Call", {"peak": 0.95, "expansion": 14.0, "compression": 2.0, "threshold": 0.0, "raise": 0.0002, "fall": 0.0002}),
        ("Subtle Normalizer", {"peak": 0.85, "expansion": 1.5, "compression": 2.0, "threshold": 0.0, "raise": 0.00001, "fall": 0.00001}),
    ],
    "compand": [
        ("Noisy Environment Listening", {"attacks": 0.3, "decays": 0.8,
                                          "points": "-90/-60|-60/-40|-40/-30|-20/-20", "soft-knee": 6.0, "gain": 0.0}),
        ("2:1 Compression", {"attacks": 0.3, "decays": 0.8,
                              "points": "-80/-80|-6/-6|0/-3.8|20/3.5", "soft-knee": 0.01, "gain": 0.0}),
        ("Gentle Leveler", {"attacks": 0.5, "decays": 1.0,
                             "points": "-70/-70|-40/-35|-20/-18|0/-2", "soft-knee": 4.0, "gain": 0.0}),
        ("Night Listening", {"attacks": 0.3, "decays": 0.8,
                              "points": "-90/-50|-50/-35|-30/-25|-10/-12|0/-8", "soft-knee": 6.0, "gain": 0.0}),
        ("Broadcast Curve", {"attacks": 0.2, "decays": 0.5,
                              "points": "-70/-70|-30/-25|-15/-12|0/-3", "soft-knee": 2.0, "gain": 0.0}),
        ("Expand Quiet", {"attacks": 0.3, "decays": 0.8,
                           "points": "-90/-90|-60/-70|-40/-50|-20/-25|0/0", "soft-knee": 2.0, "gain": 0.0}),
        ("Hard Limiter", {"attacks": 0.01, "decays": 0.2,
                           "points": "-60/-60|-10/-10|0/-1|10/-0.5", "soft-knee": 0.0, "gain": 0.0}),
        ("Soft Limiter", {"attacks": 0.1, "decays": 0.5,
                           "points": "-60/-60|-10/-9.5|0/-2", "soft-knee": 5.0, "gain": 0.0}),
        ("Vintage Radio", {"attacks": 0.1, "decays": 0.3,
                            "points": "-50/-50|-30/-25|-15/-11|0/-2", "soft-knee": 1.0, "gain": 2.0}),
        ("Cassette Warmth", {"attacks": 0.4, "decays": 1.0,
                              "points": "-80/-80|-40/-36|-20/-17|0/-3", "soft-knee": 3.0, "gain": 1.0}),
        ("Dialogue Clarity", {"attacks": 0.2, "decays": 0.4,
                               "points": "-70/-65|-40/-32|-25/-18|0/-4", "soft-knee": 3.0, "gain": 0.0}),
        ("Loudness Max", {"attacks": 0.05, "decays": 0.3,
                           "points": "-70/-70|-40/-30|-20/-12|0/-1", "soft-knee": 1.0, "gain": 3.0}),
        ("Fast Attack", {"attacks": 0.01, "decays": 0.5,
                          "points": "-70/-70|-30/-28|0/-4", "soft-knee": 2.0, "gain": 0.0}),
        ("Slow Attack", {"attacks": 1.0, "decays": 2.0,
                          "points": "-70/-70|-30/-26|0/-4", "soft-knee": 2.0, "gain": 0.0}),
        ("Aggressive Duck", {"attacks": 0.05, "decays": 1.5,
                              "points": "-70/-70|-40/-28|-20/-10|0/-2", "soft-knee": 1.0, "gain": 0.0}),
        ("Subtle Warmth", {"attacks": 0.5, "decays": 1.2,
                            "points": "-80/-78|-40/-37|-20/-18.5|0/-3.5", "soft-knee": 5.0, "gain": 0.5}),
        ("Podcast Chain", {"attacks": 0.3, "decays": 0.7,
                            "points": "-70/-68|-40/-33|-20/-16|0/-3", "soft-knee": 3.0, "gain": 1.0}),
        ("Master Glue", {"attacks": 0.4, "decays": 0.9,
                          "points": "-80/-80|-40/-37|-20/-18|0/-3", "soft-knee": 4.0, "gain": 0.0}),
        ("Half Mix Compand", {"attacks": 0.3, "decays": 0.8,
                               "points": "-80/-80|-6/-6|0/-3.8|20/3.5", "soft-knee": 0.01, "gain": 0.0}),
        ("Extreme Squash", {"attacks": 0.02, "decays": 0.2,
                             "points": "-70/-70|-40/-25|-20/-8|0/-0.5", "soft-knee": 0.5, "gain": 2.0}),
    ],
    "deesser": [
        ("Mild De-ess", {"i": 0.3, "m": 0.4, "f": 0.6, "s": "o"}),
        ("Strong De-ess", {"i": 0.6, "m": 0.7, "f": 0.4, "s": "o"}),
        ("Subtle Polish", {"i": 0.15, "m": 0.3, "f": 0.7, "s": "o"}),
        ("Harsh Sibilance", {"i": 0.8, "m": 0.8, "f": 0.3, "s": "o"}),
        ("Broadcast Voice", {"i": 0.4, "m": 0.5, "f": 0.5, "s": "o"}),
        ("Podcast Vocal", {"i": 0.35, "m": 0.45, "f": 0.55, "s": "o"}),
        ("Gentle Air Keep", {"i": 0.2, "m": 0.35, "f": 0.8, "s": "o"}),
        ("Aggressive Tame", {"i": 0.9, "m": 0.9, "f": 0.2, "s": "o"}),
        ("Wide Band De-ess", {"i": 0.5, "m": 0.6, "f": 0.1, "s": "o"}),
        ("Narrow Band De-ess", {"i": 0.5, "m": 0.6, "f": 0.9, "s": "o"}),
        ("Monitor Input", {"i": 0.5, "m": 0.5, "f": 0.5, "s": "i"}),
        ("Sidechain Only", {"i": 0.5, "m": 0.5, "f": 0.5, "s": "e"}),
        ("Female Vocal", {"i": 0.45, "m": 0.55, "f": 0.45, "s": "o"}),
        ("Male Vocal", {"i": 0.3, "m": 0.4, "f": 0.6, "s": "o"}),
        ("Voiceover", {"i": 0.4, "m": 0.5, "f": 0.5, "s": "o"}),
        ("Audiobook", {"i": 0.35, "m": 0.5, "f": 0.55, "s": "o"}),
        ("Half Mix De-ess", {"i": 0.5, "m": 0.5, "f": 0.5, "s": "o"}),
        ("Max Intensity", {"i": 1.0, "m": 1.0, "f": 0.5, "s": "o"}),
        ("Min Intensity", {"i": 0.05, "m": 0.2, "f": 0.5, "s": "o"}),
        ("Balanced Default+", {"i": 0.5, "m": 0.5, "f": 0.5, "s": "o"}),
    ],
    "flanger": [
        ("Classic Flange", {"delay": 0.0, "depth": 2.0, "regen": 0.0, "width": 71.0, "speed": 0.5,
                             "shape": "sinusoidal", "phase": 25.0, "interp": "linear"}),
        ("Jet Sweep", {"delay": 2.0, "depth": 6.0, "regen": 40.0, "width": 90.0, "speed": 0.2,
                        "shape": "sinusoidal", "phase": 25.0, "interp": "linear"}),
        ("Subtle Shimmer", {"delay": 0.5, "depth": 1.0, "regen": 10.0, "width": 50.0, "speed": 0.3,
                             "shape": "sinusoidal", "phase": 25.0, "interp": "linear"}),
        ("Through-Zero", {"delay": 0.0, "depth": 4.0, "regen": 80.0, "width": 100.0, "speed": 0.4,
                           "shape": "sinusoidal", "phase": 50.0, "interp": "linear"}),
        ("Slow Drift", {"delay": 1.0, "depth": 3.0, "regen": 20.0, "width": 71.0, "speed": 0.1,
                         "shape": "triangular", "phase": 25.0, "interp": "linear"}),
        ("Fast Wobble", {"delay": 1.0, "depth": 3.0, "regen": 30.0, "width": 71.0, "speed": 3.0,
                          "shape": "sinusoidal", "phase": 25.0, "interp": "linear"}),
        ("Triangular Sweep", {"delay": 1.0, "depth": 4.0, "regen": 25.0, "width": 80.0, "speed": 0.5,
                               "shape": "triangular", "phase": 25.0, "interp": "linear"}),
        ("Quadratic Smooth", {"delay": 1.0, "depth": 3.0, "regen": 20.0, "width": 71.0, "speed": 0.5,
                               "shape": "sinusoidal", "phase": 25.0, "interp": "quadratic"}),
        ("Wide Stereo", {"delay": 1.0, "depth": 4.0, "regen": 30.0, "width": 100.0, "speed": 0.3,
                          "shape": "sinusoidal", "phase": 75.0, "interp": "linear"}),
        ("Narrow Focus", {"delay": 1.0, "depth": 2.0, "regen": 15.0, "width": 30.0, "speed": 0.5,
                           "shape": "sinusoidal", "phase": 25.0, "interp": "linear"}),
        ("Deep Regen", {"delay": 1.5, "depth": 5.0, "regen": 70.0, "width": 85.0, "speed": 0.25,
                         "shape": "sinusoidal", "phase": 40.0, "interp": "linear"}),
        ("Guitar Sweep", {"delay": 0.8, "depth": 3.5, "regen": 50.0, "width": 75.0, "speed": 0.6,
                           "shape": "sinusoidal", "phase": 30.0, "interp": "linear"}),
        ("Vocal Robot", {"delay": 0.3, "depth": 5.0, "regen": 60.0, "width": 90.0, "speed": 1.5,
                          "shape": "triangular", "phase": 50.0, "interp": "linear"}),
        ("Ambient Movement", {"delay": 2.0, "depth": 2.5, "regen": 15.0, "width": 95.0, "speed": 0.08,
                               "shape": "sinusoidal", "phase": 25.0, "interp": "quadratic"}),
        ("Half Mix Flange", {"delay": 1.0, "depth": 3.0, "regen": 20.0, "width": 71.0, "speed": 0.5,
                              "shape": "sinusoidal", "phase": 25.0, "interp": "linear"}),
        ("Sci-fi Sweep", {"delay": 3.0, "depth": 8.0, "regen": 90.0, "width": 100.0, "speed": 0.15,
                           "shape": "triangular", "phase": 60.0, "interp": "linear"}),
        ("Light Chorus-y", {"delay": 3.0, "depth": 1.5, "regen": 5.0, "width": 60.0, "speed": 0.4,
                             "shape": "sinusoidal", "phase": 25.0, "interp": "linear"}),
        ("Percussive Flange", {"delay": 0.2, "depth": 2.0, "regen": 45.0, "width": 70.0, "speed": 2.0,
                                "shape": "triangular", "phase": 25.0, "interp": "linear"}),
        ("Max Depth", {"delay": 1.0, "depth": 10.0, "regen": 50.0, "width": 71.0, "speed": 0.5,
                        "shape": "sinusoidal", "phase": 25.0, "interp": "linear"}),
        ("Vintage 70s", {"delay": 1.2, "depth": 4.5, "regen": 55.0, "width": 80.0, "speed": 0.35,
                          "shape": "sinusoidal", "phase": 35.0, "interp": "linear"}),
    ],
    "chorus": [
        ("Subtle Thicken", {"in_gain": 0.5, "out_gain": 0.5, "delays": "40", "decays": "0.3",
                             "speeds": "0.2", "depths": "1.5"}),
        ("Lush 80s Chorus", {"in_gain": 0.4, "out_gain": 0.4, "delays": "55", "decays": "0.4",
                              "speeds": "0.25", "depths": "2"}),
        ("Wide Doubler", {"in_gain": 0.5, "out_gain": 0.5, "delays": "25", "decays": "0.5",
                           "speeds": "0.8", "depths": "3"}),
        ("Deep Choir", {"in_gain": 0.4, "out_gain": 0.4, "delays": "60|80", "decays": "0.4|0.35",
                         "speeds": "0.2|0.3", "depths": "2.5|3"}),
        ("Fast Shimmer", {"in_gain": 0.5, "out_gain": 0.5, "delays": "30", "decays": "0.4",
                           "speeds": "2.0", "depths": "2"}),
        ("Slow Ocean", {"in_gain": 0.5, "out_gain": 0.5, "delays": "80", "decays": "0.5",
                         "speeds": "0.1", "depths": "4"}),
        ("Guitar Sparkle", {"in_gain": 0.45, "out_gain": 0.45, "delays": "35", "decays": "0.35",
                             "speeds": "0.5", "depths": "2"}),
        ("Vocal Sweetener", {"in_gain": 0.4, "out_gain": 0.4, "delays": "50", "decays": "0.3",
                              "speeds": "0.35", "depths": "1.8"}),
        ("Triple Voice", {"in_gain": 0.35, "out_gain": 0.35, "delays": "40|55|70", "decays": "0.35|0.3|0.25",
                           "speeds": "0.25|0.35|0.45", "depths": "2|2.5|3"}),
        ("Detune Feel", {"in_gain": 0.5, "out_gain": 0.5, "delays": "18", "decays": "0.6",
                          "speeds": "0.15", "depths": "1"}),
        ("Ambient Wash", {"in_gain": 0.5, "out_gain": 0.5, "delays": "90|120", "decays": "0.55|0.5",
                           "speeds": "0.12|0.18", "depths": "4|5"}),
        ("Synth Pad", {"in_gain": 0.45, "out_gain": 0.45, "delays": "65", "decays": "0.45",
                        "speeds": "0.22", "depths": "3.5"}),
        ("Bass Chorus", {"in_gain": 0.5, "out_gain": 0.5, "delays": "15", "decays": "0.3",
                          "speeds": "0.3", "depths": "1.2"}),
        ("Vintage Chorus", {"in_gain": 0.4, "out_gain": 0.4, "delays": "45", "decays": "0.4",
                             "speeds": "0.28", "depths": "2.2"}),
        ("Half Mix Chorus", {"in_gain": 0.5, "out_gain": 0.5, "delays": "50", "decays": "0.4",
                              "speeds": "0.25", "depths": "2"}),
        ("Pronounced Mod", {"in_gain": 0.5, "out_gain": 0.5, "delays": "50", "decays": "0.7",
                             "speeds": "0.6", "depths": "5"}),
        ("Light Air", {"in_gain": 0.5, "out_gain": 0.5, "delays": "60", "decays": "0.15",
                        "speeds": "0.2", "depths": "1"}),
        ("Leslie Feel", {"in_gain": 0.45, "out_gain": 0.45, "delays": "35|50", "decays": "0.4|0.4",
                          "speeds": "1.2|1.8", "depths": "2|2.5"}),
        ("Dreamy Drift", {"in_gain": 0.5, "out_gain": 0.5, "delays": "75", "decays": "0.6",
                           "speeds": "0.08", "depths": "4.5"}),
        ("Tight Ensemble", {"in_gain": 0.4, "out_gain": 0.4, "delays": "20|28|36", "decays": "0.3|0.3|0.3",
                             "speeds": "0.4|0.5|0.6", "depths": "1.5|1.5|1.5"}),
    ],
    "tremolo": [
        ("Subtle Pulse", {"f": 4.0, "d": 0.3}),
        ("Classic Amp Tremolo", {"f": 6.0, "d": 0.6}),
        ("Ring Mod (Extreme)", {"f": 50.0, "d": 1.0}),
        ("Slow Sway", {"f": 1.0, "d": 0.4}),
        ("Very Slow Drift", {"f": 0.5, "d": 0.3}),
        ("Fast Shutter", {"f": 12.0, "d": 0.7}),
        ("Helicopter", {"f": 20.0, "d": 0.9}),
        ("Gentle Breeze", {"f": 2.0, "d": 0.2}),
        ("Vintage Fender", {"f": 5.0, "d": 0.5}),
        ("Surf Rock", {"f": 7.0, "d": 0.75}),
        ("Machine Gun", {"f": 15.0, "d": 1.0}),
        ("Wobble Bass", {"f": 8.0, "d": 0.8}),
        ("Heartbeat", {"f": 1.5, "d": 0.6}),
        ("Light Shimmer", {"f": 3.0, "d": 0.15}),
        ("Half Mix Trem", {"f": 5.0, "d": 0.5}),
        ("Deep Throb", {"f": 3.0, "d": 0.85}),
        ("Tremolo Soft", {"f": 5.0, "d": 0.25}),
        ("Tremolo Hard", {"f": 5.0, "d": 0.95}),
        ("Sci-fi Pulsing", {"f": 30.0, "d": 0.8}),
        ("Organ Leslie-ish", {"f": 10.0, "d": 0.5}),
    ],
    "vibrato": [
        ("Gentle Vibrato", {"f": 5.0, "d": 0.3}),
        ("Wide Vibrato", {"f": 7.0, "d": 0.7}),
        ("Opera Singer", {"f": 6.0, "d": 0.5}),
        ("Subtle Warmth", {"f": 4.0, "d": 0.15}),
        ("Fast Nervous", {"f": 9.0, "d": 0.4}),
        ("Extreme Wobble", {"f": 5.0, "d": 1.0}),
        ("Slow Siren", {"f": 1.0, "d": 0.6}),
        ("Very Slow Drift", {"f": 0.5, "d": 0.4}),
        ("Violin Vibrato", {"f": 6.5, "d": 0.35}),
        ("Guitar Vibrato", {"f": 5.5, "d": 0.25}),
        ("Synth Wobble", {"f": 8.0, "d": 0.6}),
        ("Alien Voice", {"f": 3.0, "d": 0.9}),
        ("Tape Warble", {"f": 0.8, "d": 0.2}),
        ("Light Shimmer", {"f": 5.0, "d": 0.1}),
        ("Half Mix Vib", {"f": 5.0, "d": 0.5}),
        ("Deep Pitch Bend", {"f": 2.0, "d": 0.8}),
        ("Vibrato Soft", {"f": 5.0, "d": 0.2}),
        ("Vibrato Hard", {"f": 5.0, "d": 0.9}),
        ("Sci-fi Warble", {"f": 12.0, "d": 0.7}),
        ("Leslie Speed", {"f": 7.5, "d": 0.45}),
    ],
    "pulsator": [
        ("Slow Autopan", {"level_in": 1.0, "level_out": 1.0, "mode": "sine", "amount": 1.0,
                           "offset_l": 0.0, "offset_r": 0.5, "width": 1.0, "hz": 0.5}),
        ("Tremolo (Synced)", {"level_in": 1.0, "level_out": 1.0, "mode": "square", "amount": 1.0,
                               "offset_l": 0.0, "offset_r": 0.0, "width": 1.0, "hz": 4.0}),
        ("Gentle Pulse", {"level_in": 1.0, "level_out": 1.0, "mode": "sine", "amount": 0.5,
                           "offset_l": 0.0, "offset_r": 0.0, "width": 1.0, "hz": 2.0}),
        ("Fast Trance Gate", {"level_in": 1.0, "level_out": 1.0, "mode": "square", "amount": 1.0,
                               "offset_l": 0.0, "offset_r": 0.0, "width": 0.5, "hz": 8.0}),
        ("Saw Rhythm", {"level_in": 1.0, "level_out": 1.0, "mode": "sawup", "amount": 1.0,
                         "offset_l": 0.0, "offset_r": 0.0, "width": 1.0, "hz": 4.0}),
        ("Reverse Saw", {"level_in": 1.0, "level_out": 1.0, "mode": "sawdown", "amount": 1.0,
                          "offset_l": 0.0, "offset_r": 0.0, "width": 1.0, "hz": 4.0}),
        ("Triangle Wave", {"level_in": 1.0, "level_out": 1.0, "mode": "triangle", "amount": 1.0,
                            "offset_l": 0.0, "offset_r": 0.0, "width": 1.0, "hz": 3.0}),
        ("Wide Autopan", {"level_in": 1.0, "level_out": 1.0, "mode": "sine", "amount": 1.0,
                           "offset_l": 0.0, "offset_r": 0.5, "width": 2.0, "hz": 0.25}),
        ("Fast Autopan", {"level_in": 1.0, "level_out": 1.0, "mode": "sine", "amount": 1.0,
                           "offset_l": 0.0, "offset_r": 0.5, "width": 1.0, "hz": 2.0}),
        ("Subtle Movement", {"level_in": 1.0, "level_out": 1.0, "mode": "sine", "amount": 0.3,
                              "offset_l": 0.0, "offset_r": 0.25, "width": 1.0, "hz": 0.8}),
        ("Heartbeat", {"level_in": 1.0, "level_out": 1.0, "mode": "sine", "amount": 0.8,
                        "offset_l": 0.0, "offset_r": 0.0, "width": 0.3, "hz": 1.2}),
        ("LFO Wobble", {"level_in": 1.0, "level_out": 1.0, "mode": "triangle", "amount": 0.9,
                         "offset_l": 0.0, "offset_r": 0.0, "width": 1.0, "hz": 0.5}),
        ("Gated Pad", {"level_in": 1.0, "level_out": 1.0, "mode": "square", "amount": 1.0,
                        "offset_l": 0.0, "offset_r": 0.0, "width": 0.4, "hz": 6.0}),
        ("Half Mix Pulse", {"level_in": 1.0, "level_out": 1.0, "mode": "sine", "amount": 1.0,
                             "offset_l": 0.0, "offset_r": 0.0, "width": 1.0, "hz": 4.0}),
        ("Slow Fade Pulse", {"level_in": 1.0, "level_out": 1.0, "mode": "sine", "amount": 0.6,
                              "offset_l": 0.0, "offset_r": 0.0, "width": 1.0, "hz": 0.2}),
        ("Ping Pong Pan", {"level_in": 1.0, "level_out": 1.0, "mode": "triangle", "amount": 1.0,
                            "offset_l": 0.0, "offset_r": 0.5, "width": 1.0, "hz": 1.0}),
        ("Stutter Effect", {"level_in": 1.0, "level_out": 1.0, "mode": "square", "amount": 1.0,
                             "offset_l": 0.0, "offset_r": 0.0, "width": 0.2, "hz": 16.0}),
        ("Breathing", {"level_in": 1.0, "level_out": 1.0, "mode": "sine", "amount": 0.4,
                        "offset_l": 0.0, "offset_r": 0.0, "width": 1.0, "hz": 0.15}),
        ("Dance Pulse", {"level_in": 1.0, "level_out": 1.0, "mode": "sawup", "amount": 0.8,
                          "offset_l": 0.0, "offset_r": 0.0, "width": 0.8, "hz": 5.0}),
        ("Max Amount", {"level_in": 1.0, "level_out": 1.0, "mode": "sine", "amount": 1.0,
                         "offset_l": 0.0, "offset_r": 0.0, "width": 1.0, "hz": 4.0}),
    ],
    "phaser": [
        ("Classic Phaser", {"in_gain": 0.4, "out_gain": 0.74, "delay": 3.0, "decay": 0.4,
                             "speed": 0.5, "type": "triangular"}),
        ("Slow Sweep", {"in_gain": 0.4, "out_gain": 0.74, "delay": 3.0, "decay": 0.6,
                         "speed": 0.15, "type": "sinusoidal"}),
        ("Fast Sweep", {"in_gain": 0.4, "out_gain": 0.74, "delay": 3.0, "decay": 0.4,
                         "speed": 2.0, "type": "triangular"}),
        ("Subtle Phase", {"in_gain": 0.4, "out_gain": 0.74, "delay": 1.0, "decay": 0.2,
                           "speed": 0.5, "type": "sinusoidal"}),
        ("Deep Phase", {"in_gain": 0.5, "out_gain": 0.8, "delay": 5.0, "decay": 0.8,
                         "speed": 0.3, "type": "triangular"}),
        ("Sci-fi Sweep", {"in_gain": 0.5, "out_gain": 0.9, "delay": 4.0, "decay": 0.9,
                           "speed": 0.8, "type": "sinusoidal"}),
        ("Guitar 70s", {"in_gain": 0.4, "out_gain": 0.74, "delay": 3.0, "decay": 0.5,
                         "speed": 0.4, "type": "triangular"}),
        ("Vocal Robot", {"in_gain": 0.45, "out_gain": 0.8, "delay": 2.0, "decay": 0.7,
                          "speed": 1.5, "type": "sinusoidal"}),
        ("Sweep Down", {"in_gain": 0.4, "out_gain": 0.74, "delay": 5.0, "decay": 0.5,
                         "speed": 0.2, "type": "triangular"}),
        ("Light Shimmer", {"in_gain": 0.4, "out_gain": 0.74, "delay": 2.0, "decay": 0.15,
                            "speed": 0.6, "type": "sinusoidal"}),
        ("Half Mix Phase", {"in_gain": 0.4, "out_gain": 0.74, "delay": 3.0, "decay": 0.4,
                             "speed": 0.5, "type": "triangular"}),
        ("Jet Plane", {"in_gain": 0.5, "out_gain": 0.85, "delay": 4.5, "decay": 0.85,
                        "speed": 0.25, "type": "sinusoidal"}),
        ("Wah-like", {"in_gain": 0.4, "out_gain": 0.74, "delay": 1.5, "decay": 0.6,
                       "speed": 3.0, "type": "triangular"}),
        ("Ambient Drift", {"in_gain": 0.4, "out_gain": 0.74, "delay": 4.0, "decay": 0.3,
                            "speed": 0.08, "type": "sinusoidal"}),
        ("Percussive Phase", {"in_gain": 0.4, "out_gain": 0.74, "delay": 2.0, "decay": 0.5,
                               "speed": 4.0, "type": "triangular"}),
        ("Max Decay", {"in_gain": 0.4, "out_gain": 0.74, "delay": 3.0, "decay": 0.98,
                        "speed": 0.5, "type": "triangular"}),
        ("Min Decay", {"in_gain": 0.4, "out_gain": 0.74, "delay": 3.0, "decay": 0.05,
                        "speed": 0.5, "type": "triangular"}),
        ("Slow Deep", {"in_gain": 0.45, "out_gain": 0.78, "delay": 4.5, "decay": 0.7,
                        "speed": 0.1, "type": "triangular"}),
        ("Fast Light", {"in_gain": 0.4, "out_gain": 0.74, "delay": 2.0, "decay": 0.25,
                         "speed": 5.0, "type": "sinusoidal"}),
        ("Vintage Vibes", {"in_gain": 0.42, "out_gain": 0.76, "delay": 3.5, "decay": 0.45,
                            "speed": 0.35, "type": "triangular"}),
    ],
    "pitch_shift": [
        ("One Octave Up", {"pitch-scale": 2.0, "engine": "finer"}),
        ("One Octave Down", {"pitch-scale": 0.5, "engine": "finer"}),
        ("Subtle Detune", {"pitch-scale": 1.05, "engine": "finer"}),
        ("Half Step Up", {"pitch-scale": 1.059463, "engine": "finer"}),
        ("Half Step Down", {"pitch-scale": 0.943874, "engine": "finer"}),
        ("Whole Step Up", {"pitch-scale": 1.122462, "engine": "finer"}),
        ("Whole Step Down", {"pitch-scale": 0.890899, "engine": "finer"}),
        ("Minor Third Up", {"pitch-scale": 1.189207, "engine": "finer"}),
        ("Major Third Up", {"pitch-scale": 1.259921, "engine": "finer"}),
        ("Fourth Up", {"pitch-scale": 1.334840, "engine": "finer"}),
        ("Fifth Up", {"pitch-scale": 1.498307, "engine": "finer"}),
        ("Chipmunk", {"pitch-scale": 1.5, "engine": "faster"}),
        ("Deep Voice", {"pitch-scale": 0.7, "engine": "faster"}),
        ("Monster", {"pitch-scale": 0.5, "engine": "faster"}),
        ("Slight Brighten", {"pitch-scale": 1.02, "engine": "finer"}),
        ("Slight Darken", {"pitch-scale": 0.98, "engine": "finer"}),
        ("Quarter Tone Up", {"pitch-scale": 1.029302, "engine": "finer"}),
        ("Quarter Tone Down", {"pitch-scale": 0.971532, "engine": "finer"}),
        ("Two Octaves Up", {"pitch-scale": 4.0, "engine": "faster"}),
        ("Two Octaves Down", {"pitch-scale": 0.25, "engine": "faster"}),
    ],
    "tempo_scale": [
        ("Half Speed", {"scale": 1, "speed": "none"}),
        ("Double Speed", {"scale": 2, "speed": "none"}),
        ("Quarter Speed", {"scale": 1, "speed": "none"}),
        ("Triple Speed", {"scale": 3, "speed": "none"}),
        ("1.5x Speed", {"scale": 1, "speed": "none"}),
        ("Slow Practice", {"scale": 1, "speed": "none"}),
        ("Fast Practice", {"scale": 2, "speed": "none"}),
        ("Pitch Preserved", {"scale": 1, "speed": "pitch"}),
        ("Half Speed Pitch", {"scale": 1, "speed": "pitch"}),
        ("Double Speed Pitch", {"scale": 2, "speed": "pitch"}),
        ("Slight Slow", {"scale": 1, "speed": "none"}),
        ("Slight Fast", {"scale": 1, "speed": "none"}),
        ("Max Slow", {"scale": 1, "speed": "none"}),
        ("Max Fast", {"scale": 25, "speed": "none"}),
        ("Half Mix Tempo", {"scale": 1, "speed": "none"}),
        ("Study Pace", {"scale": 1, "speed": "none"}),
        ("Transcription Slow", {"scale": 1, "speed": "none"}),
        ("Podcast 2x", {"scale": 2, "speed": "pitch"}),
        ("Podcast 1.5x", {"scale": 1, "speed": "pitch"}),
        ("Audiobook Fast", {"scale": 2, "speed": "pitch"}),
    ],
    "extrastereo": [
        ("Subtle Widen", {"m": 1.5, "c": "true"}),
        ("Wide Stage", {"m": 3.5, "c": "true"}),
        ("Slight Widen", {"m": 1.2, "c": "true"}),
        ("Moderate Widen", {"m": 2.0, "c": "true"}),
        ("Strong Widen", {"m": 5.0, "c": "true"}),
        ("Extreme Widen", {"m": 8.0, "c": "true"}),
        ("Narrow In", {"m": 0.5, "c": "true"}),
        ("Mono Fold", {"m": 0.0, "c": "true"}),
        ("Invert Phase", {"m": -1.0, "c": "true"}),
        ("Slight Narrow", {"m": 0.8, "c": "true"}),
        ("No Clipping Guard", {"m": 2.0, "c": "false"}),
        ("Safe Widen", {"m": 1.8, "c": "true"}),
        ("Half Mix Wide", {"m": 2.5, "c": "true"}),
        ("Concert Hall Feel", {"m": 3.0, "c": "true"}),
        ("Headphone Expand", {"m": 2.8, "c": "true"}),
        ("Subtle Air", {"m": 1.35, "c": "true"}),
        ("Max Safe", {"m": 10.0, "c": "true"}),
        ("Gentle Narrow", {"m": 0.7, "c": "true"}),
        ("Cinema Wide", {"m": 4.0, "c": "true"}),
        ("Default+", {"m": 2.5, "c": "true"}),
    ],
    "stereowiden": [
        ("Gentle Widen", {"delay": 15.0, "feedback": 0.2, "crossfeed": 0.2, "drymix": 0.85}),
        ("Wide Stage", {"delay": 25.0, "feedback": 0.4, "crossfeed": 0.4, "drymix": 0.7}),
        ("Subtle Space", {"delay": 10.0, "feedback": 0.1, "crossfeed": 0.1, "drymix": 0.92}),
        ("Moderate Widen", {"delay": 20.0, "feedback": 0.3, "crossfeed": 0.3, "drymix": 0.8}),
        ("Strong Widen", {"delay": 30.0, "feedback": 0.5, "crossfeed": 0.5, "drymix": 0.6}),
        ("Extreme Wide", {"delay": 40.0, "feedback": 0.6, "crossfeed": 0.6, "drymix": 0.5}),
        ("Haas-like", {"delay": 35.0, "feedback": 0.2, "crossfeed": 0.3, "drymix": 0.75}),
        ("Narrow Focus", {"delay": 8.0, "feedback": 0.15, "crossfeed": 0.15, "drymix": 0.9}),
        ("Ambient Expand", {"delay": 28.0, "feedback": 0.45, "crossfeed": 0.45, "drymix": 0.65}),
        ("Concert Space", {"delay": 22.0, "feedback": 0.35, "crossfeed": 0.35, "drymix": 0.75}),
        ("Headphone Out", {"delay": 18.0, "feedback": 0.25, "crossfeed": 0.25, "drymix": 0.82}),
        ("Deep Space", {"delay": 45.0, "feedback": 0.7, "crossfeed": 0.7, "drymix": 0.4}),
        ("Light Touch", {"delay": 12.0, "feedback": 0.12, "crossfeed": 0.12, "drymix": 0.9}),
        ("Half Mix Widen", {"delay": 20.0, "feedback": 0.3, "crossfeed": 0.3, "drymix": 0.8}),
        ("Vintage Wide", {"delay": 26.0, "feedback": 0.38, "crossfeed": 0.38, "drymix": 0.72}),
        ("Max Feedback", {"delay": 25.0, "feedback": 0.85, "crossfeed": 0.4, "drymix": 0.7}),
        ("Min Feedback", {"delay": 25.0, "feedback": 0.05, "crossfeed": 0.4, "drymix": 0.7}),
        ("Dry Forward", {"delay": 20.0, "feedback": 0.3, "crossfeed": 0.3, "drymix": 0.95}),
        ("Wet Back", {"delay": 20.0, "feedback": 0.3, "crossfeed": 0.3, "drymix": 0.5}),
        ("Balanced Default+", {"delay": 20.0, "feedback": 0.3, "crossfeed": 0.3, "drymix": 0.8}),
    ],
    "stereotools": [
        ("Mid/Side Widen", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                             "mode": "lr>lr", "base": 0.4, "phase": 0.0}),
        ("Mono Downmix", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                           "mode": "lr>l+r", "base": 0.0, "phase": 0.0}),
        ("Left Only", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                        "mode": "lr>ll", "base": 0.0, "phase": 0.0}),
        ("Right Only", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                         "mode": "lr>rr", "base": 0.0, "phase": 0.0}),
        ("Swap Channels", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                            "mode": "lr>rl", "base": 0.0, "phase": 0.0}),
        ("Sum Mono", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                       "mode": "lr>l+r", "base": 0.0, "phase": 0.0}),
        ("Difference Side", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                              "mode": "lr>l-r", "base": 0.0, "phase": 0.0}),
        ("Mid to LR", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                        "mode": "ms>lr", "base": 0.0, "phase": 0.0}),
        ("LR to Mid", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                        "mode": "lr>ms", "base": 0.0, "phase": 0.0}),
        ("Slight Narrow", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                            "mode": "lr>lr", "base": -0.3, "phase": 0.0}),
        ("Wide Base", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                        "mode": "lr>lr", "base": 0.8, "phase": 0.0}),
        ("Balance Left", {"level_in": 1.0, "level_out": 1.0, "balance_in": -0.5, "balance_out": 0.0,
                           "mode": "lr>lr", "base": 0.0, "phase": 0.0}),
        ("Balance Right", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.5, "balance_out": 0.0,
                            "mode": "lr>lr", "base": 0.0, "phase": 0.0}),
        ("Phase Invert 180", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                               "mode": "lr>lr", "base": 0.0, "phase": 180.0}),
        ("Phase 90", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                       "mode": "lr>lr", "base": 0.0, "phase": 90.0}),
        ("Boost Output", {"level_in": 1.0, "level_out": 2.0, "balance_in": 0.0, "balance_out": 0.0,
                           "mode": "lr>lr", "base": 0.0, "phase": 0.0}),
        ("Attenuate Output", {"level_in": 1.0, "level_out": 0.5, "balance_in": 0.0, "balance_out": 0.0,
                               "mode": "lr>lr", "base": 0.0, "phase": 0.0}),
        ("Half Mix Tools", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                             "mode": "lr>lr", "base": 0.2, "phase": 0.0}),
        ("Karaoke Remove Vocal", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                                   "mode": "lr>l-r", "base": 0.0, "phase": 0.0}),
        ("Default+", {"level_in": 1.0, "level_out": 1.0, "balance_in": 0.0, "balance_out": 0.0,
                       "mode": "lr>lr", "base": 0.0, "phase": 0.0}),
    ],
    "haas": [
        ("Mono-to-Stereo Widen", {"level_in": 1.0, "level_out": 1.0, "side_gain": 1.0,
                                   "middle_source": "mid", "left_delay": 2.05, "right_delay": 15.0}),
        ("Subtle Haas", {"level_in": 1.0, "level_out": 1.0, "side_gain": 0.5,
                          "middle_source": "mid", "left_delay": 2.05, "right_delay": 8.0}),
        ("Strong Haas", {"level_in": 1.0, "level_out": 1.0, "side_gain": 1.5,
                          "middle_source": "mid", "left_delay": 2.05, "right_delay": 25.0}),
        ("Left Source", {"level_in": 1.0, "level_out": 1.0, "side_gain": 1.0,
                          "middle_source": "left", "left_delay": 2.05, "right_delay": 15.0}),
        ("Right Source", {"level_in": 1.0, "level_out": 1.0, "side_gain": 1.0,
                           "middle_source": "right", "left_delay": 2.05, "right_delay": 15.0}),
        ("Side Source", {"level_in": 1.0, "level_out": 1.0, "side_gain": 1.0,
                          "middle_source": "side", "left_delay": 2.05, "right_delay": 15.0}),
        ("Short Delay", {"level_in": 1.0, "level_out": 1.0, "side_gain": 1.0,
                          "middle_source": "mid", "left_delay": 2.05, "right_delay": 5.0}),
        ("Long Delay", {"level_in": 1.0, "level_out": 1.0, "side_gain": 1.0,
                         "middle_source": "mid", "left_delay": 2.05, "right_delay": 35.0}),
        ("Boost Side", {"level_in": 1.0, "level_out": 1.0, "side_gain": 2.0,
                         "middle_source": "mid", "left_delay": 2.05, "right_delay": 15.0}),
        ("Cut Side", {"level_in": 1.0, "level_out": 1.0, "side_gain": 0.2,
                       "middle_source": "mid", "left_delay": 2.05, "right_delay": 15.0}),
        ("Mono Safe", {"level_in": 1.0, "level_out": 1.0, "side_gain": 1.0,
                        "middle_source": "mid", "left_delay": 2.05, "right_delay": 12.0}),
        ("Wide Fake Stereo", {"level_in": 1.0, "level_out": 1.0, "side_gain": 1.2,
                               "middle_source": "mid", "left_delay": 2.05, "right_delay": 20.0}),
        ("Half Mix Haas", {"level_in": 1.0, "level_out": 1.0, "side_gain": 1.0,
                            "middle_source": "mid", "left_delay": 2.05, "right_delay": 15.0}),
        ("Guitar Widen", {"level_in": 1.0, "level_out": 1.0, "side_gain": 0.8,
                           "middle_source": "mid", "left_delay": 2.05, "right_delay": 18.0}),
        ("Vocal Widen", {"level_in": 1.0, "level_out": 1.0, "side_gain": 0.6,
                          "middle_source": "mid", "left_delay": 2.05, "right_delay": 10.0}),
        ("Ambience Boost", {"level_in": 1.0, "level_out": 1.0, "side_gain": 1.4,
                             "middle_source": "side", "left_delay": 2.05, "right_delay": 22.0}),
        ("Pseudo Stereo", {"level_in": 1.0, "level_out": 1.0, "side_gain": 1.0,
                            "middle_source": "left", "left_delay": 2.05, "right_delay": 20.0}),
        ("Tight Haas", {"level_in": 1.0, "level_out": 1.0, "side_gain": 0.8,
                         "middle_source": "mid", "left_delay": 2.05, "right_delay": 4.0}),
        ("Loose Haas", {"level_in": 1.0, "level_out": 1.0, "side_gain": 1.0,
                         "middle_source": "mid", "left_delay": 2.05, "right_delay": 30.0}),
        ("Default+", {"level_in": 1.0, "level_out": 1.0, "side_gain": 1.0,
                       "middle_source": "mid", "left_delay": 2.05, "right_delay": 15.0}),
    ],
    "bs2b": [
        ("Default Headphone", {"profile": "default", "fcut": 700, "feed": 50}),
        ("Chu Moy", {"profile": "cmoy", "fcut": 700, "feed": 60}),
        ("Jan Meier", {"profile": "jmeier", "fcut": 650, "feed": 95}),
        ("Low Freq Cut", {"profile": "default", "fcut": 500, "feed": 50}),
        ("High Freq Cut", {"profile": "default", "fcut": 1000, "feed": 50}),
        ("Gentle Feed", {"profile": "default", "fcut": 700, "feed": 30}),
        ("Strong Feed", {"profile": "default", "fcut": 700, "feed": 80}),
        ("Max Feed", {"profile": "default", "fcut": 700, "feed": 150}),
        ("Min Feed", {"profile": "default", "fcut": 700, "feed": 10}),
        ("CMoy Gentle", {"profile": "cmoy", "fcut": 600, "feed": 45}),
        ("CMoy Strong", {"profile": "cmoy", "fcut": 800, "feed": 80}),
        ("JMeier Gentle", {"profile": "jmeier", "fcut": 600, "feed": 70}),
        ("JMeier Strong", {"profile": "jmeier", "fcut": 700, "feed": 120}),
        ("Bass Preserve", {"profile": "default", "fcut": 400, "feed": 60}),
        ("Treble Preserve", {"profile": "default", "fcut": 1200, "feed": 40}),
        ("Half Mix BS2B", {"profile": "default", "fcut": 700, "feed": 50}),
        ("Bright Crossfeed", {"profile": "cmoy", "fcut": 900, "feed": 55}),
        ("Warm Crossfeed", {"profile": "jmeier", "fcut": 550, "feed": 85}),
        ("Subtle Crossfeed", {"profile": "default", "fcut": 700, "feed": 20}),
        ("Heavy Crossfeed", {"profile": "jmeier", "fcut": 700, "feed": 140}),
    ],
    "crossfeed": [
        ("Subtle Headphone Crossfeed", {"strength": 0.15, "range": 0.5, "slope": 0.5, "level_in": 0.9, "level_out": 1.0}),
        ("Strong Speaker-Like", {"strength": 0.5, "range": 0.7, "slope": 0.3, "level_in": 0.9, "level_out": 1.0}),
        ("Gentle", {"strength": 0.2, "range": 0.5, "slope": 0.5, "level_in": 1.0, "level_out": 1.0}),
        ("Moderate", {"strength": 0.3, "range": 0.6, "slope": 0.4, "level_in": 0.9, "level_out": 1.0}),
        ("Maximum", {"strength": 1.0, "range": 0.8, "slope": 0.2, "level_in": 0.9, "level_out": 1.0}),
        ("Minimum", {"strength": 0.05, "range": 0.4, "slope": 0.6, "level_in": 0.9, "level_out": 1.0}),
        ("Wide Stage", {"strength": 0.3, "range": 0.9, "slope": 0.5, "level_in": 0.9, "level_out": 1.0}),
        ("Narrow Stage", {"strength": 0.3, "range": 0.2, "slope": 0.5, "level_in": 0.9, "level_out": 1.0}),
        ("Steep Slope", {"strength": 0.3, "range": 0.5, "slope": 0.01, "level_in": 0.9, "level_out": 1.0}),
        ("Gentle Slope", {"strength": 0.3, "range": 0.5, "slope": 1.0, "level_in": 0.9, "level_out": 1.0}),
        ("Boost Input", {"strength": 0.3, "range": 0.5, "slope": 0.5, "level_in": 1.5, "level_out": 1.0}),
        ("Cut Input", {"strength": 0.3, "range": 0.5, "slope": 0.5, "level_in": 0.5, "level_out": 1.0}),
        ("Boost Output", {"strength": 0.3, "range": 0.5, "slope": 0.5, "level_in": 0.9, "level_out": 1.5}),
        ("Cut Output", {"strength": 0.3, "range": 0.5, "slope": 0.5, "level_in": 0.9, "level_out": 0.6}),
        ("Half Mix Crossfeed", {"strength": 0.3, "range": 0.5, "slope": 0.5, "level_in": 0.9, "level_out": 1.0}),
        ("Speaker Simulation", {"strength": 0.6, "range": 0.7, "slope": 0.3, "level_in": 0.9, "level_out": 1.0}),
        ("Comfort Listening", {"strength": 0.25, "range": 0.55, "slope": 0.45, "level_in": 0.9, "level_out": 1.0}),
        ("Bass Keep", {"strength": 0.3, "range": 0.3, "slope": 0.3, "level_in": 0.9, "level_out": 1.0}),
        ("Air Keep", {"strength": 0.3, "range": 0.7, "slope": 0.7, "level_in": 0.9, "level_out": 1.0}),
        ("Default+", {"strength": 0.2, "range": 0.5, "slope": 0.5, "level_in": 0.9, "level_out": 1.0}),
    ],
    "denoise_fft": [
        ("Light Hiss Reduction", {"nr": 6.0, "nf": -50.0, "nt": "white", "tn": "false"}),
        ("Vinyl Crackle", {"nr": 12.0, "nf": -45.0, "nt": "vinyl", "tn": "false"}),
        ("Adaptive/Field Recording", {"nr": 15.0, "nf": -50.0, "nt": "white", "tn": "true"}),
        ("Gentle Cleanup", {"nr": 3.0, "nf": -55.0, "nt": "white", "tn": "false"}),
        ("Moderate Hiss", {"nr": 9.0, "nf": -50.0, "nt": "white", "tn": "false"}),
        ("Strong Hiss", {"nr": 20.0, "nf": -45.0, "nt": "white", "tn": "false"}),
        ("Max Reduction", {"nr": 50.0, "nf": -40.0, "nt": "white", "tn": "false"}),
        ("Shellac 78s", {"nr": 14.0, "nf": -45.0, "nt": "shellac", "tn": "false"}),
        ("Custom Noise Profile", {"nr": 12.0, "nf": -50.0, "nt": "custom", "tn": "false"}),
        ("Track Noise Follow", {"nr": 10.0, "nf": -50.0, "nt": "white", "tn": "true"}),
        ("High Floor", {"nr": 12.0, "nf": -30.0, "nt": "white", "tn": "false"}),
        ("Low Floor", {"nr": 12.0, "nf": -80.0, "nt": "white", "tn": "false"}),
        ("Podcast Voice", {"nr": 8.0, "nf": -52.0, "nt": "white", "tn": "true"}),
        ("Interview Cleanup", {"nr": 10.0, "nf": -50.0, "nt": "white", "tn": "true"}),
        ("Half Mix Denoise", {"nr": 12.0, "nf": -50.0, "nt": "white", "tn": "false"}),
        ("Hum Focused", {"nr": 18.0, "nf": -48.0, "nt": "vinyl", "tn": "true"}),
        ("Studio Dialogue", {"nr": 7.0, "nf": -55.0, "nt": "white", "tn": "true"}),
        ("Aggressive Clean", {"nr": 30.0, "nf": -42.0, "nt": "white", "tn": "false"}),
        ("Preserve Air", {"nr": 5.0, "nf": -60.0, "nt": "white", "tn": "false"}),
        ("Balanced Default+", {"nr": 12.0, "nf": -50.0, "nt": "white", "tn": "false"}),
    ],
    "denoise_nlm": [
        ("Gentle", {"s": 0.00003, "p": 2.0, "r": 6.0, "m": 11.0}),
        ("Strong", {"s": 0.001, "p": 4.0, "r": 12.0, "m": 15.0}),
        ("Very Gentle", {"s": 0.00001, "p": 2.0, "r": 6.0, "m": 11.0}),
        ("Moderate", {"s": 0.0001, "p": 3.0, "r": 8.0, "m": 12.0}),
        ("Heavy", {"s": 0.01, "p": 5.0, "r": 15.0, "m": 20.0}),
        ("Maximum", {"s": 1.0, "p": 6.0, "r": 20.0, "m": 25.0}),
        ("Small Patch", {"s": 0.0001, "p": 1.0, "r": 4.0, "m": 11.0}),
        ("Large Patch", {"s": 0.0001, "p": 10.0, "r": 20.0, "m": 11.0}),
        ("Small Research", {"s": 0.0001, "p": 2.0, "r": 2.0, "m": 11.0}),
        ("Large Research", {"s": 0.0001, "p": 2.0, "r": 50.0, "m": 11.0}),
        ("Smooth", {"s": 0.0001, "p": 2.0, "r": 6.0, "m": 50.0}),
        ("Detailed", {"s": 0.0001, "p": 2.0, "r": 6.0, "m": 1.0}),
        ("Podcast Voice", {"s": 0.00005, "p": 2.0, "r": 6.0, "m": 11.0}),
        ("Field Recording", {"s": 0.0005, "p": 3.0, "r": 10.0, "m": 14.0}),
        ("Half Mix NLM", {"s": 0.0001, "p": 2.0, "r": 6.0, "m": 11.0}),
        ("Hiss Focus", {"s": 0.00002, "p": 2.0, "r": 8.0, "m": 11.0}),
        ("Broadband Noise", {"s": 0.005, "p": 4.0, "r": 12.0, "m": 15.0}),
        ("Preserve Detail", {"s": 0.00005, "p": 2.0, "r": 6.0, "m": 5.0}),
        ("Aggressive Smooth", {"s": 0.05, "p": 5.0, "r": 15.0, "m": 30.0}),
        ("Balanced Default+", {"s": 0.0001, "p": 2.0, "r": 6.0, "m": 11.0}),
    ],
    "crystalizer": [
        ("Add Sparkle", {"i": 2.0, "c": "true"}),
        ("Subtle Sharpen", {"i": 0.8, "c": "true"}),
        ("Light Touch", {"i": 0.5, "c": "true"}),
        ("Moderate", {"i": 1.5, "c": "true"}),
        ("Strong", {"i": 3.0, "c": "true"}),
        ("Extreme", {"i": 5.0, "c": "true"}),
        ("Maximum", {"i": 10.0, "c": "true"}),
        ("Negative Soften", {"i": -1.0, "c": "true"}),
        ("Strong Soften", {"i": -3.0, "c": "true"}),
        ("Max Soften", {"i": -10.0, "c": "true"}),
        ("No Clipping Guard", {"i": 2.0, "c": "false"}),
        ("Safe Sparkle", {"i": 1.2, "c": "true"}),
        ("Half Mix Crystal", {"i": 2.0, "c": "true"}),
        ("Percussion Snap", {"i": 2.5, "c": "true"}),
        ("Vocal Clarity", {"i": 1.0, "c": "true"}),
        ("Cymbal Air", {"i": 3.5, "c": "true"}),
        ("Gentle Negative", {"i": -0.5, "c": "true"}),
        ("Detail Boost", {"i": 1.8, "c": "true"}),
        ("Smooth Digital", {"i": -2.0, "c": "true"}),
        ("Default+", {"i": 2.0, "c": "true"}),
    ],
    "exciter": [
        ("Vocal Presence", {"level_in": 1.0, "level_out": 1.0, "amount": 1.0, "drive": 8.5,
                             "blend": 0.0, "freq": 7500.0, "ceil": 9999.0}),
        ("Air/Sparkle", {"level_in": 1.0, "level_out": 1.0, "amount": 2.0, "drive": 6.0,
                          "blend": 2.0, "freq": 9000.0, "ceil": 15000.0}),
        ("Subtle Enhance", {"level_in": 1.0, "level_out": 1.0, "amount": 0.5, "drive": 5.0,
                             "blend": 0.0, "freq": 8000.0, "ceil": 12000.0}),
        ("Moderate Enhance", {"level_in": 1.0, "level_out": 1.0, "amount": 1.5, "drive": 7.0,
                               "blend": 1.0, "freq": 8000.0, "ceil": 13000.0}),
        ("Strong Enhance", {"level_in": 1.0, "level_out": 1.0, "amount": 3.0, "drive": 9.0,
                             "blend": 3.0, "freq": 7000.0, "ceil": 15000.0}),
        ("Extreme Enhance", {"level_in": 1.0, "level_out": 1.0, "amount": 6.0, "drive": 10.0,
                              "blend": 5.0, "freq": 6000.0, "ceil": 18000.0}),
        ("Low Harmonics", {"level_in": 1.0, "level_out": 1.0, "amount": 2.0, "drive": 8.0,
                            "blend": 0.0, "freq": 3000.0, "ceil": 9999.0}),
        ("High Harmonics", {"level_in": 1.0, "level_out": 1.0, "amount": 2.0, "drive": 8.0,
                             "blend": 0.0, "freq": 11000.0, "ceil": 18000.0}),
        ("Heavy Drive", {"level_in": 1.0, "level_out": 1.0, "amount": 2.0, "drive": 10.0,
                          "blend": 0.0, "freq": 7500.0, "ceil": 9999.0}),
        ("Light Drive", {"level_in": 1.0, "level_out": 1.0, "amount": 2.0, "drive": 2.0,
                          "blend": 0.0, "freq": 7500.0, "ceil": 9999.0}),
        ("Negative Blend", {"level_in": 1.0, "level_out": 1.0, "amount": 2.0, "drive": 8.5,
                             "blend": -5.0, "freq": 7500.0, "ceil": 9999.0}),
        ("Positive Blend", {"level_in": 1.0, "level_out": 1.0, "amount": 2.0, "drive": 8.5,
                             "blend": 5.0, "freq": 7500.0, "ceil": 9999.0}),
        ("Boost Output", {"level_in": 1.0, "level_out": 1.5, "amount": 1.0, "drive": 8.5,
                           "blend": 0.0, "freq": 7500.0, "ceil": 9999.0}),
        ("Cut Output", {"level_in": 1.0, "level_out": 0.7, "amount": 1.0, "drive": 8.5,
                         "blend": 0.0, "freq": 7500.0, "ceil": 9999.0}),
        ("Half Mix Excite", {"level_in": 1.0, "level_out": 1.0, "amount": 1.0, "drive": 8.5,
                              "blend": 0.0, "freq": 7500.0, "ceil": 9999.0}),
        ("Dull Recording Fix", {"level_in": 1.0, "level_out": 1.0, "amount": 2.5, "drive": 7.0,
                                 "blend": 1.5, "freq": 6500.0, "ceil": 14000.0}),
        ("Bright Master", {"level_in": 1.0, "level_out": 1.0, "amount": 1.2, "drive": 6.0,
                            "blend": 1.0, "freq": 9500.0, "ceil": 16000.0}),
        ("Warm Master", {"level_in": 1.0, "level_out": 1.0, "amount": 0.8, "drive": 5.0,
                          "blend": -2.0, "freq": 5000.0, "ceil": 9999.0}),
        ("Cymbal Air", {"level_in": 1.0, "level_out": 1.0, "amount": 2.0, "drive": 7.0,
                         "blend": 2.0, "freq": 10000.0, "ceil": 18000.0}),
        ("Default+", {"level_in": 1.0, "level_out": 1.0, "amount": 1.0, "drive": 8.5,
                       "blend": 0.0, "freq": 7500.0, "ceil": 9999.0}),
    ],
    "equalizer": [
        ("Bass Boost", {"preamp": 0.0, "band_0": 6.0, "band_1": 4.0, "band_2": 2.0, "band_3": 0.0,
                         "band_4": 0.0, "band_5": 0.0, "band_6": 0.0, "band_7": 0.0, "band_8": 0.0, "band_9": 0.0}),
        ("Vocal Boost", {"preamp": 0.0, "band_0": -2.0, "band_1": -1.0, "band_2": 0.0, "band_3": 2.0,
                          "band_4": 4.0, "band_5": 3.0, "band_6": 2.0, "band_7": 0.0, "band_8": 0.0, "band_9": 0.0}),
        ("Treble Boost", {"preamp": 0.0, "band_0": 0.0, "band_1": 0.0, "band_2": 0.0, "band_3": 0.0,
                           "band_4": 0.0, "band_5": 1.0, "band_6": 3.0, "band_7": 5.0, "band_8": 6.0, "band_9": 6.0}),
        ("Flat", {"preamp": 0.0, "band_0": 0.0, "band_1": 0.0, "band_2": 0.0, "band_3": 0.0,
                   "band_4": 0.0, "band_5": 0.0, "band_6": 0.0, "band_7": 0.0, "band_8": 0.0, "band_9": 0.0}),
        ("Rock", {"preamp": -1.0, "band_0": 5.0, "band_1": 4.0, "band_2": 2.5, "band_3": 0.0,
                   "band_4": -1.5, "band_5": -1.0, "band_6": 1.0, "band_7": 3.0, "band_8": 4.0, "band_9": 4.5}),
        ("Pop", {"preamp": -1.0, "band_0": -1.5, "band_1": -0.5, "band_2": 0.0, "band_3": 2.5,
                  "band_4": 4.0, "band_5": 3.0, "band_6": 1.0, "band_7": -0.5, "band_8": -1.0, "band_9": -1.5}),
        ("Jazz", {"preamp": -1.0, "band_0": 3.5, "band_1": 2.5, "band_2": 1.0, "band_3": 1.5,
                   "band_4": -1.0, "band_5": -1.5, "band_6": 0.0, "band_7": 1.5, "band_8": 2.5, "band_9": 3.5}),
        ("Classical", {"preamp": -1.0, "band_0": 4.0, "band_1": 3.0, "band_2": 2.0, "band_3": 1.0,
                        "band_4": -1.0, "band_5": -1.0, "band_6": 0.0, "band_7": 2.0, "band_8": 3.0, "band_9": 4.0}),
        ("Electronic", {"preamp": -1.0, "band_0": 6.0, "band_1": 5.0, "band_2": 2.0, "band_3": 0.0,
                         "band_4": -2.0, "band_5": 1.5, "band_6": 1.0, "band_7": 2.0, "band_8": 4.0, "band_9": 5.0}),
        ("Hip-Hop", {"preamp": -1.0, "band_0": 7.0, "band_1": 5.5, "band_2": 3.0, "band_3": 1.5,
                      "band_4": -1.0, "band_5": -1.5, "band_6": 0.5, "band_7": 1.5, "band_8": 2.0, "band_9": 2.5}),
        ("Acoustic", {"preamp": -1.0, "band_0": 4.0, "band_1": 3.5, "band_2": 2.0, "band_3": 0.5,
                       "band_4": 1.5, "band_5": 2.0, "band_6": 2.5, "band_7": 3.0, "band_8": 2.5, "band_9": 1.5}),
        ("Vocal Remove (Karaoke)", {"preamp": 0.0, "band_0": 0.0, "band_1": 0.0, "band_2": 0.0, "band_3": -6.0,
                                     "band_4": -9.0, "band_5": -9.0, "band_6": -6.0, "band_7": 0.0, "band_8": 0.0, "band_9": 0.0}),
        ("Loudness", {"preamp": -2.0, "band_0": 7.0, "band_1": 5.0, "band_2": 0.0, "band_3": -2.0,
                       "band_4": -3.0, "band_5": -1.0, "band_6": 0.0, "band_7": 3.0, "band_8": 6.0, "band_9": 7.0}),
        ("Speech Clarity", {"preamp": 0.0, "band_0": -4.0, "band_1": -3.0, "band_2": 0.0, "band_3": 2.0,
                             "band_4": 4.0, "band_5": 4.0, "band_6": 3.0, "band_7": 1.0, "band_8": 0.0, "band_9": -1.0}),
        ("Late Night", {"preamp": -1.0, "band_0": 3.0, "band_1": 2.0, "band_2": 1.0, "band_3": 0.0,
                         "band_4": 0.0, "band_5": 0.0, "band_6": 1.0, "band_7": 2.0, "band_8": 3.0, "band_9": 3.0}),
        ("Bass Cut", {"preamp": 0.0, "band_0": -6.0, "band_1": -5.0, "band_2": -3.0, "band_3": -1.0,
                       "band_4": 0.0, "band_5": 0.0, "band_6": 0.0, "band_7": 0.0, "band_8": 0.0, "band_9": 0.0}),
        ("Treble Cut", {"preamp": 0.0, "band_0": 0.0, "band_1": 0.0, "band_2": 0.0, "band_3": 0.0,
                         "band_4": 0.0, "band_5": -1.0, "band_6": -3.0, "band_7": -5.0, "band_8": -6.0, "band_9": -6.0}),
        ("Smiley Curve", {"preamp": -3.0, "band_0": 6.0, "band_1": 5.0, "band_2": 3.0, "band_3": 1.0,
                           "band_4": 0.0, "band_5": 0.0, "band_6": 1.0, "band_7": 3.0, "band_8": 5.0, "band_9": 6.0}),
        ("Podcast Voice", {"preamp": 0.0, "band_0": -5.0, "band_1": -4.0, "band_2": -1.0, "band_3": 2.0,
                            "band_4": 3.5, "band_5": 3.0, "band_6": 2.0, "band_7": 0.5, "band_8": -0.5, "band_9": -1.0}),
        ("Soft", {"preamp": -1.0, "band_0": 2.0, "band_1": 1.5, "band_2": 1.0, "band_3": 0.5,
                   "band_4": 0.0, "band_5": 0.0, "band_6": 0.5, "band_7": 1.0, "band_8": 1.5, "band_9": 2.0}),
    ],
}
