#!/usr/bin/env python3

import argparse
import importlib.util
import sys
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT_DIR / "src"

sys.path.insert(0, str(SRC_DIR))

import app_info


# utilities/__init__.py imports Qt, so the pure-data formats module is loaded
# from its file instead of through the package.
def _load_formats():
    spec = importlib.util.spec_from_file_location("playform_formats", SRC_DIR / "utilities" / "formats.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _escape(value: str) -> str:
    return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def _registry(root: str, key: str, value: str, name: str = None, value_type: str = "string", key_path: bool = False) -> str:
    name_attr = f' Name="{name}"' if name else ""
    key_path_attr = ' KeyPath="yes"' if key_path else ""
    return (
        f'        <RegistryValue Root="{root}" Key="{key}"{name_attr}'
        f' Value="{value}" Type="{value_type}"{key_path_attr} />'
    )


def build_component(formats: dict, descriptions: dict) -> str:
    app_name = app_info.APP_NAME
    exe_path = f"[INSTALLFOLDER]{app_name}.exe"
    open_command = f"&quot;{exe_path}&quot; &quot;%1&quot;"
    app_key = f"Software\\Classes\\Applications\\{app_name}.exe"

    lines = [
        '        <!-- Registers PlayForm as a handler for every audio and video',
        '             format the app supports. Generated from the tables in',
        '             src/utilities/formats.py by scripts/gen_file_associations.py. -->',
    ]

    for category in ("video", "audio"):
        lines.append(f"        <!-- {category.capitalize()} formats -->")
        for ext in formats[category]:
            prog_id = f"{app_name}.{ext}"
            lines.append(_registry("HKCU", f"Software\\Classes\\.{ext}\\OpenWithProgids", "", prog_id))
            lines.append(_registry("HKCU", f"Software\\Classes\\{prog_id}", _escape(descriptions[category][ext])))
            lines.append(_registry("HKCU", f"Software\\Classes\\{prog_id}\\DefaultIcon", f"{exe_path},0"))
            lines.append(_registry("HKCU", f"Software\\Classes\\{prog_id}\\shell\\open\\command", open_command))
        lines.append("")

    lines.append(f"        <!-- {app_name} in the Windows \"Open with\" picker -->")
    lines.append(_registry("HKCU", app_key, app_name, "FriendlyAppName"))
    lines.append(_registry("HKCU", app_key, app_info.APP_PUBLISHER, "ApplicationCompany"))
    lines.append(_registry("HKCU", f"{app_key}\\DefaultIcon", f"{exe_path},0"))
    lines.append(_registry("HKCU", f"{app_key}\\shell\\open\\command", open_command))
    for category in ("video", "audio"):
        for ext in formats[category]:
            lines.append(_registry("HKCU", f"{app_key}\\SupportedTypes", "", ext))
    lines.append("")

    lines.append(_registry("HKCU", f"Software\\{app_info.APP_PUBLISHER}\\{app_name}", "1", "FileAssociations",
                           value_type="integer", key_path=True))

    body = "\n".join(lines)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!-- Generated by scripts/gen_file_associations.py - do not edit by hand.\n"
        "     Regenerate with: python scripts/gen_file_associations.py -->\n"
        '<Include xmlns="http://schemas.microsoft.com/wix/2006/wi">\n'
        "  <Fragment>\n"
        '    <DirectoryRef Id="INSTALLFOLDER">\n'
        '      <Component Id="FileAssociations" Guid="4664aae0-7a97-4f7f-b54b-2bc48603588f">\n'
        f"{body}\n"
        "      </Component>\n"
        "    </DirectoryRef>\n"
        "  </Fragment>\n"
        "</Include>\n"
    )


def main():
    parser = argparse.ArgumentParser(description="Generate the WiX file-association component from the app's format tables")
    parser.add_argument("--output", "-o", default=str(ROOT_DIR / "installer" / "windows" / "file_associations.wxi"),
                        help="Destination .wxi file")
    args = parser.parse_args()

    module = _load_formats()
    content = build_component(module.formats, module.format_descriptions)

    output_file = Path(args.output)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)

    total = sum(len(exts) for exts in module.formats.values())
    print(f"File associations generated: {output_file} ({total} formats)")


if __name__ == "__main__":
    main()
